## Importing libraries

In [1]:
#pip install pycountry

In [2]:
import pandas as pd
import requests
import pycountry

## Importing data

### Eurostat

#### Air transport of passengers

In [3]:
# Replace 'path/to/Ait transport of passengers Eurostat.xlsx' with the actual path to your Excel file
excel_file_path = 'Air transport of passengers Eurostat.xlsx'

# Read the Excel file into a Pandas DataFrame
air_df = pd.read_excel(excel_file_path)

air_df = air_df.rename(columns={'TIME': 'Country'})

# Now, you can work with the 'air_df' DataFrame as needed
air_df

,Country,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Belgium,25102695.0,25919515.0,26389927.0,28776258.0,30958841.0,30115832.0,33260493.0,34506309.0,35385188.0,9465828.0,13500020.0,27873892.0
1,Bulgaria,6652007.0,6819103.0,7079292.0,7520697.0,7610949.0,9324217.0,11092651.0,12137714.0,11713068.0,3729017.0,5047877.0,8807502.0
2,Czechia,12650532.0,11742352.0,11891812.0,12079873.0,12672004.0,13672362.0,16245554.0,17838221.0,18767088.0,3821372.0,4755160.0,11532650.0
3,Denmark,25808321.0,26532730.0,27459623.0,29015133.0,30095505.0,32763142.0,33261214.0,34701139.0,34780127.0,8658654.0,10817817.0,26649573.0
4,Germany,175316076.0,178591103.0,180783188.0,186445814.0,193936430.0,200687293.0,212389343.0,222422361.0,226764086.0,57795978.0,73597370.0,155302643.0
5,Estonia,1907569.0,2202427.0,1958565.0,2019806.0,2160978.0,2214989.0,2635145.0,2995528.0,3258003.0,857837.0,1292941.0,2731365.0
6,Ireland,23362889.0,23594089.0,24603640.0,26310826.0,29545020.0,32595709.0,34271771.0,36345005.0,37947510.0,8268297.0,9097359.0,32405890.0
7,Greece,33770739.0,32082336.0,34023934.0,39117833.0,42096402.0,45543371.0,50170728.0,54258826.0,56088527.0,17341192.0,32245559.0,57893929.0
8,Spain,165153230.0,159771261.0,157731973.0,165354382.0,174652503.0,193872037.0,209824089.0,220611429.0,228262372.0,57797305.0,91898241.0,199571203.0
9,France,126013257.0,129764462.0,132762875.0,136360671.0,140867569.0,145280602.0,154096485.0,161991179.0,168726788.0,50724011.0,66033809.0,136560938.0
10,Croatia,4989236.0,5422632.0,5722447.0,6140797.0,6571698.0,7475463.0,8843053.0,9731294.0,10623239.0,1943547.0,4458400.0,9415321.0
11,Italy,116226667.0,116029388.0,115279105.0,121164587.0,127665221.0,134477781.0,144306325.0,153352444.0,160667939.0,40405355.0,59709143.0,132425719.0
12,Cyprus,7190387.0,7328300.0,7011437.0,7328546.0,7590787.0,8961817.0,10238913.0,10927101.0,11261410.0,2270577.0,5099704.0,8613471.0
13,Latvia,5098360.0,4754530.0,4782257.0,4802282.0,5145856.0,5384160.0,6077854.0,7037070.0,7785726.0,1995133.0,2336134.0,5368369.0
14,Lithuania,2691991.0,3166628.0,3482358.0,3798110.0,4227389.0,4787561.0,5246101.0,6254178.0,6504685.0,1804500.0,2464603.0,5333890.0
15,Luxembourg,1836780.0,1893991.0,2169327.0,2433966.0,2651751.0,2984242.0,3554730.0,3988804.0,4365569.0,1426310.0,2002903.0,4057247.0
16,Hungary,8884837.0,8429843.0,8441319.0,9054848.0,10228352.0,11660366.0,13350029.0,15176493.0,16700750.0,3962687.0,4665369.0,12393512.0
17,Malta,3506814.0,3650347.0,4032029.0,4290032.0,4619557.0,5080446.0,6007731.0,6805817.0,7318357.0,1752445.0,2547912.0,5861597.0
18,Netherlands,53895292.0,55680209.0,58077271.0,60963003.0,64570938.0,70317995.0,76240304.0,79644163.0,81192507.0,23594783.0,29082583.0,61289771.0
19,Austria,25137612.0,25965977.0,25749724.0,26378676.0,26754007.0,27181511.0,28327279.0,31138417.0,35644188.0,9168431.0,11105564.0,26381180.0
20,Poland,20635672.0,21800765.0,23274484.0,25714422.0,28907439.0,32266861.0,37684668.0,43767548.0,46942771.0,13825460.0,18893812.0,39347542.0
21,Portugal,27579707.0,28186254.0,29694146.0,32560621.0,36005814.0,40930044.0,47673057.0,51018598.0,55007894.0,16548993.0,22347692.0,57081723.0
22,Romania,9687456.0,9674226.0,10016933.0,10907487.0,12580711.0,15153719.0,17934774.0,19809642.0,21565865.0,6633447.0,10384613.0,19535951.0
23,Slovenia,1358792.0,1167877.0,1265766.0,1307128.0,1436003.0,1404152.0,1682133.0,1810567.0,1719039.0,287787.0,419346.0,968811.0
24,Slovakia,1808187.0,1563197.0,1557149.0,1671290.0,1943656.0,2158261.0,2402651.0,2794094.0,2839787.0,500604.0,642078.0,1942568.0
25,Finland,16374398.0,16458815.0,16565391.0,17171931.0,17479246.0,18099954.0,20054947.0,22173530.0,23287929.0,5428622.0,4554497.0,13812577.0
26,Sweden,29732247.0,30350849.0,31443225.0,32766043.0,34011263.0,35952558.0,38456213.0,38945096.0,37614763.0,9317677.0,10798009.0,25038812.0
27,Iceland,2462894.0,2740691.0,3199266.0,3853614.0,4847288.0,6801814.0,8318734.0,10166386.0,7584197.0,1527633.0,2437139.0,6463479.0
28,Liechtenstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Norway,32403522.0,34592225.0,36686364.0,37603195.0,37503052.0,37727546.0,38739778.0,40030105.0,40348437.0,13216883.0,14136316.0,32562643.0
30,Switzerland,41439848.0,43236086.0,44217568.0,46127426.0,48026375.0,50505492.0,53564943.0,56139549.0,57194328.0,16006811.0,19109708.0,42424182.0
31,United Kingdom,201536753.0,203067015.0,210468980.0,220022122.0,232270437.0,248868873.0,264629454.0,272190155.0,277432380.0,NaN,NaN,NaN
32,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,987659.0,NaN
33,Montenegro,NaN,NaN,NaN,NaN,NaN,1845464.0,2173494.0,2440486.0,2652801.0,521959.0,1309266.0,1908552.0
34,North Macedonia,NaN,NaN,NaN,NaN,1452373.0,1649374.0,1861282.0,2152746.0,2353327.0,709241.0,1266230.0,2134988.0
35,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Serbia,NaN,NaN,NaN,NaN,NaN,4414858.0,4828171.0,5521250.0,6450643.0,1938468.0,3431750.0,5991693.0
37,Türkiye,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Rail transport of passengers

In [4]:
# Replace 'Rail transport of passengers.xlsx'
excel_file_path = 'Rail transport of passengers Eurostat.xlsx'

# Read the Excel file into a Pandas DataFrame
rail_df = pd.read_excel(excel_file_path)

rail_df = rail_df.rename(columns={'TIME': 'Country'})

# Now, you can work with the 'air_df' DataFrame as needed
rail_df

,Country,2011,Unnamed: 2,2012,Unnamed: 4,2013,Unnamed: 6,2014,Unnamed: 8,2015,...,Unnamed: 14,2018,Unnamed: 16,2019,Unnamed: 18,2020,Unnamed: 20,2021,Unnamed: 22,2022
0,Belgium,10498.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bulgaria,2059.0,NaN,1870.0,NaN,1821.0,NaN,1698.0,NaN,1549.0,...,NaN,1476.0,NaN,1520.0,NaN,1118.0,NaN,1203.0,NaN,1600.0
2,zehia,NaN,NaN,7196.0,NaN,7512.0,NaN,7644.0,NaN,8125.0,...,NaN,10220.0,NaN,10856.0,NaN,6623.0,NaN,6752.0,NaN,9394.0
3,Denmark,6395.0,NaN,6534.0,NaN,6566.0,NaN,6513.0,NaN,6507.0,...,NaN,6182.0,NaN,6174.0,NaN,3940.0,NaN,4181.0,NaN,6376.0
4,Germany,89316.0,NaN,93918.0,NaN,89450.0,NaN,90978.0,NaN,91050.0,...,NaN,98161.0,NaN,100252.0,NaN,57787.0,NaN,57518.0,NaN,92313.0
5,Estonia,243.0,NaN,235.0,NaN,223.0,NaN,280.0,NaN,286.0,...,NaN,417.0,NaN,392.0,NaN,263.0,NaN,290.0,NaN,382.0
6,Ireland,1638.0,NaN,1578.0,NaN,1569.0,NaN,1728.0,NaN,1918.0,...,NaN,2281.0,NaN,2399.0,NaN,834.0,NaN,870.0,NaN,1748.0
7,Greee,958.0,NaN,832.0,NaN,1056.0,NaN,1072.0,NaN,1263.0,...,NaN,1104.0,NaN,1252.0,NaN,640.0,NaN,653.0,NaN,1117.0
8,Spain,22645.0,NaN,22170.0,NaN,23660.0,NaN,24915.0,NaN,26018.0,...,NaN,28317.0,NaN,28703.0,NaN,11987.0,NaN,17002.0,NaN,27489.0
9,Frane,91298.0,NaN,91205.0,NaN,90485.0,NaN,89499.0,NaN,91377.0,...,NaN,91818.0,NaN,96540.0,NaN,56606.0,NaN,75854.0,NaN,102814.0
10,roatia,1457.0,NaN,1080.0,NaN,935.0,NaN,917.0,NaN,941.0,...,NaN,747.0,NaN,724.0,NaN,448.0,NaN,538.0,NaN,812.0
11,Italy,45944.0,NaN,45753.0,NaN,47707.0,NaN,48881.0,NaN,51121.0,...,NaN,55037.0,NaN,56160.0,NaN,22064.0,NaN,27444.0,NaN,46143.0
12,yprus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Latvia,733.0,NaN,717.0,NaN,721.0,NaN,644.0,NaN,590.0,...,NaN,624.0,NaN,643.0,NaN,413.0,NaN,361.0,NaN,541.0
14,Lithuania,269.0,NaN,278.0,NaN,278.0,NaN,270.0,NaN,262.0,...,NaN,354.0,NaN,359.0,NaN,237.0,NaN,287.0,NaN,382.0
15,Luxembourg,349.0,NaN,373.0,NaN,394.0,NaN,366.0,NaN,418.0,...,NaN,443.0,NaN,463.0,NaN,268.0,NaN,304.0,NaN,389.0
16,Hungary,7763.0,NaN,7769.0,NaN,7806.0,NaN,7710.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Malta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Netherlands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Austria,10172.0,NaN,10606.0,NaN,11188.0,NaN,11345.0,NaN,11433.0,...,NaN,12681.0,NaN,12761.0,NaN,6964.0,NaN,8054.0,NaN,12371.0
20,Poland,17633.0,NaN,17110.0,NaN,16453.0,NaN,15479.0,NaN,17024.0,...,NaN,20849.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23646.0
21,Portugal,4237.0,NaN,3803.0,NaN,3649.0,NaN,3852.0,NaN,3957.0,...,NaN,4570.0,NaN,5055.0,NaN,2563.0,NaN,2912.0,NaN,4419.0
22,Romania,5044.0,NaN,4518.0,NaN,4352.0,NaN,4971.0,NaN,4910.0,...,NaN,5426.0,NaN,5735.0,NaN,3609.0,NaN,4104.0,NaN,5616.0
23,Slovenia,689.0,NaN,659.0,NaN,679.0,NaN,620.0,NaN,628.0,...,NaN,568.0,NaN,572.0,NaN,338.0,NaN,504.0,NaN,645.0
24,Slovakia,2431.0,NaN,2459.0,NaN,2485.0,NaN,2583.0,NaN,3411.0,...,NaN,3792.0,NaN,3957.0,NaN,2133.0,NaN,1969.0,NaN,3168.0
25,Finland,3882.0,NaN,4035.0,NaN,4053.0,NaN,3874.0,NaN,4114.0,...,NaN,4535.0,NaN,4924.0,NaN,2820.0,NaN,2903.0,NaN,4572.0
26,Sweden,11379.0,NaN,11792.0,NaN,11842.0,NaN,12121.0,NaN,12741.0,...,NaN,13547.0,NaN,14617.0,NaN,8129.0,NaN,8027.0,NaN,12879.0
27,Ieland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Liehtenstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Norway,3076.0,NaN,3092.0,NaN,3260.0,NaN,3440.0,NaN,3555.0,...,NaN,3722.0,NaN,3715.0,NaN,1801.0,NaN,1780.0,NaN,3079.0
30,Switzerland,18320.0,NaN,18115.0,NaN,18277.0,NaN,18801.0,NaN,19089.0,...,NaN,19245.0,NaN,20315.0,NaN,12419.0,NaN,13321.0,NaN,18022.0
31,United Kingdom,58462.0,NaN,60783.0,NaN,61950.0,NaN,64711.0,NaN,66594.0,...,NaN,69706.0,NaN,71823.0,NaN,NaN,NaN,NaN,NaN,NaN
32,Montenegro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,North Maedonia,145.0,NaN,99.0,NaN,80.0,NaN,80.0,NaN,177.0,...,NaN,63.0,NaN,62.0,NaN,25.0,NaN,25.0,NaN,46.0
34,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Türkiye,5882.0,NaN,4598.0,NaN,3775.0,NaN,4393.0,NaN,4828.0,...,NaN,5560.0,NaN,11068.0,NaN,6094.0,NaN,8544.0,NaN,NaN

In [5]:
# Drop columns with all NaN values
rail_df = rail_df.dropna(axis=1, how='all')

# Display the cleaned DataFrame
rail_df

,Country,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Belgium,10498.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bulgaria,2059.0,1870.0,1821.0,1698.0,1549.0,1455.0,1434.0,1476.0,1520.0,1118.0,1203.0,1600.0
2,zehia,NaN,7196.0,7512.0,7644.0,8125.0,8738.0,9403.0,10220.0,10856.0,6623.0,6752.0,9394.0
3,Denmark,6395.0,6534.0,6566.0,6513.0,6507.0,6332.0,6280.0,6182.0,6174.0,3940.0,4181.0,6376.0
4,Germany,89316.0,93918.0,89450.0,90978.0,91050.0,95465.0,95529.0,98161.0,100252.0,57787.0,57518.0,92313.0
5,Estonia,243.0,235.0,223.0,280.0,286.0,316.0,366.0,417.0,392.0,263.0,290.0,382.0
6,Ireland,1638.0,1578.0,1569.0,1728.0,1918.0,1991.0,2122.0,2281.0,2399.0,834.0,870.0,1748.0
7,Greee,958.0,832.0,1056.0,1072.0,1263.0,1192.0,1112.0,1104.0,1252.0,640.0,653.0,1117.0
8,Spain,22645.0,22170.0,23660.0,24915.0,26018.0,26532.0,27374.0,28317.0,28703.0,11987.0,17002.0,27489.0
9,Frane,91298.0,91205.0,90485.0,89499.0,91377.0,91832.0,95024.0,91818.0,96540.0,56606.0,75854.0,102814.0
10,roatia,1457.0,1080.0,935.0,917.0,941.0,827.0,736.0,747.0,724.0,448.0,538.0,812.0
11,Italy,45944.0,45753.0,47707.0,48881.0,51121.0,51716.0,52778.0,55037.0,56160.0,22064.0,27444.0,46143.0
12,yprus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Latvia,733.0,717.0,721.0,644.0,590.0,584.0,596.0,624.0,643.0,413.0,361.0,541.0
14,Lithuania,269.0,278.0,278.0,270.0,262.0,280.0,315.0,354.0,359.0,237.0,287.0,382.0
15,Luxembourg,349.0,373.0,394.0,366.0,418.0,417.0,438.0,443.0,463.0,268.0,304.0,389.0
16,Hungary,7763.0,7769.0,7806.0,7710.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Malta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Netherlands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Austria,10172.0,10606.0,11188.0,11345.0,11433.0,12021.0,12077.0,12681.0,12761.0,6964.0,8054.0,12371.0
20,Poland,17633.0,17110.0,16453.0,15479.0,17024.0,18753.0,20120.0,20849.0,NaN,NaN,NaN,23646.0
21,Portugal,4237.0,3803.0,3649.0,3852.0,3957.0,4266.0,4516.0,4570.0,5055.0,2563.0,2912.0,4419.0
22,Romania,5044.0,4518.0,4352.0,4971.0,4910.0,4731.0,5556.0,5426.0,5735.0,3609.0,4104.0,5616.0
23,Slovenia,689.0,659.0,679.0,620.0,628.0,611.0,570.0,568.0,572.0,338.0,504.0,645.0
24,Slovakia,2431.0,2459.0,2485.0,2583.0,3411.0,3484.0,3754.0,3792.0,3957.0,2133.0,1969.0,3168.0
25,Finland,3882.0,4035.0,4053.0,3874.0,4114.0,3868.0,4271.0,4535.0,4924.0,2820.0,2903.0,4572.0
26,Sweden,11379.0,11792.0,11842.0,12121.0,12741.0,12800.0,13331.0,13547.0,14617.0,8129.0,8027.0,12879.0
27,Ieland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Liehtenstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Norway,3076.0,3092.0,3260.0,3440.0,3555.0,3695.0,3584.0,3722.0,3715.0,1801.0,1780.0,3079.0
30,Switzerland,18320.0,18115.0,18277.0,18801.0,19089.0,19573.0,19586.0,19245.0,20315.0,12419.0,13321.0,18022.0
31,United Kingdom,58462.0,60783.0,61950.0,64711.0,66594.0,68010.0,68912.0,69706.0,71823.0,NaN,NaN,NaN
32,Montenegro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,North Maedonia,145.0,99.0,80.0,80.0,177.0,83.0,59.0,63.0,62.0,25.0,25.0,46.0
34,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Türkiye,5882.0,4598.0,3775.0,4393.0,4828.0,4325.0,4566.0,5560.0,11068.0,6094.0,8544.0,NaN

### World Bank

#### Population

In [6]:
# Specify the file path
file_path = 'Population World Bank.csv'

# Read the CSV file into a DataFrame
population_df = pd.read_csv(file_path)

# Now, 'population_df' contains your data from the CSV file
population_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54608.0,55811.0,56682.0,57475.0,58178.0,58782.0,...,102880.0,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0,106445.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,...,567892149.0,583651101.0,600008424.0,616377605.0,632746570.0,649757148.0,667242986.0,685112979.0,702977106.0,720859132.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,...,31541209.0,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,41128771.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97256290.0,99314028.0,101445032.0,103667517.0,105959979.0,108336203.0,...,387204553.0,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0,490330870.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,5357195.0,5441333.0,5521400.0,5599827.0,5673199.0,5736582.0,...,26147002.0,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0,35588987.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population, total",SP.POP.TOTL,947000.0,966000.0,994000.0,1022000.0,1050000.0,1078000.0,...,1818117.0,1812771.0,1788196.0,1777557.0,1791003.0,1797085.0,1788878.0,1790133.0,1786038.0,1761985.0
262,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5542459.0,5646668.0,5753386.0,5860197.0,5973803.0,6097298.0,...,26984002.0,27753304.0,28516545.0,29274002.0,30034389.0,30790513.0,31546691.0,32284046.0,32981641.0,33696614.0
263,South Africa,ZAF,"Population, total",SP.POP.TOTL,16520441.0,16989464.0,17503133.0,18042215.0,18603097.0,19187194.0,...,53873616.0,54729551.0,55876504.0,56422274.0,56641209.0,57339635.0,58087055.0,58801927.0,59392255.0,59893885.0
264,Zambia,ZMB,"Population, total",SP.POP.TOTL,3119430.0,3219451.0,3323427.0,3431381.0,3542764.0,3658024.0,...,15234976.0,15737793.0,16248230.0,16767761.0,17298054.0,17835893.0,18380477.0,18927715.0,19473125.0,20017675.0
265,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3806310.0,3925952.0,4049778.0,4177931.0,4310332.0,4447149.0,...,13555422.0,13855753.0,14154937.0,14452704.0,14751101.0,15052184.0,15354608.0,15669666.0,15993524.0,16320537.0

#### Income

In [7]:
# Replace 'path_to_your_file' with the actual path to your CSV file
file_path = 'Average income world bank.csv'

# Read the CSV file into a Pandas DataFrame
income_df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame to verify the import
income_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,22115.614210,23111.232220,24093.582640,24018.878420,24457.602270,24859.525440,26702.132160,20971.438090,24994.772990,NaN
1,Africa Eastern and Southern,AFE,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1327.021073,1343.347342,1236.498033,1167.651297,1313.117754,1257.046421,1228.514026,1113.051649,1232.351821,NaN
2,Afghanistan,AFG,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,598.899585,577.260184,550.241360,485.792229,498.041221,467.286034,469.477760,476.899060,339.682114,NaN
3,Africa Western and Central,AFW,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1679.965667,1838.464813,1589.531108,1397.764260,1316.043520,1412.503047,1440.327860,1399.151980,1415.982509,NaN
4,Angola,AGO,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3187.601761,3490.921523,2374.531996,1207.215215,1501.637531,1507.863453,1328.708143,1100.962834,1232.948233,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,"Yemen, Rep.",YEM,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1273.489211,1323.269168,1366.411677,1016.887235,849.030933,665.907750,NaN,NaN,NaN,NaN
263,South Africa,ZAF,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5977.137238,5646.961218,5127.603776,4681.677958,5505.776036,5740.363783,5449.048686,4658.248020,5717.120396,NaN
264,Zambia,ZMB,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1409.081210,1375.312762,1050.129153,988.532254,1138.740164,1142.799848,1010.373209,698.249518,614.647305,NaN
265,Zimbabwe,ZWE,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1118.834349,1081.898309,1088.188448,1082.175060,907.633691,1980.607561,1218.164067,1161.171249,1472.254411,NaN

## Dataframes standatrization

In [8]:
rail_df = rail_df.rename(columns={'Country': 'Country Name'})
rail_df

,Country Name,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Belgium,10498.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bulgaria,2059.0,1870.0,1821.0,1698.0,1549.0,1455.0,1434.0,1476.0,1520.0,1118.0,1203.0,1600.0
2,zehia,NaN,7196.0,7512.0,7644.0,8125.0,8738.0,9403.0,10220.0,10856.0,6623.0,6752.0,9394.0
3,Denmark,6395.0,6534.0,6566.0,6513.0,6507.0,6332.0,6280.0,6182.0,6174.0,3940.0,4181.0,6376.0
4,Germany,89316.0,93918.0,89450.0,90978.0,91050.0,95465.0,95529.0,98161.0,100252.0,57787.0,57518.0,92313.0
5,Estonia,243.0,235.0,223.0,280.0,286.0,316.0,366.0,417.0,392.0,263.0,290.0,382.0
6,Ireland,1638.0,1578.0,1569.0,1728.0,1918.0,1991.0,2122.0,2281.0,2399.0,834.0,870.0,1748.0
7,Greee,958.0,832.0,1056.0,1072.0,1263.0,1192.0,1112.0,1104.0,1252.0,640.0,653.0,1117.0
8,Spain,22645.0,22170.0,23660.0,24915.0,26018.0,26532.0,27374.0,28317.0,28703.0,11987.0,17002.0,27489.0
9,Frane,91298.0,91205.0,90485.0,89499.0,91377.0,91832.0,95024.0,91818.0,96540.0,56606.0,75854.0,102814.0
10,roatia,1457.0,1080.0,935.0,917.0,941.0,827.0,736.0,747.0,724.0,448.0,538.0,812.0
11,Italy,45944.0,45753.0,47707.0,48881.0,51121.0,51716.0,52778.0,55037.0,56160.0,22064.0,27444.0,46143.0
12,yprus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Latvia,733.0,717.0,721.0,644.0,590.0,584.0,596.0,624.0,643.0,413.0,361.0,541.0
14,Lithuania,269.0,278.0,278.0,270.0,262.0,280.0,315.0,354.0,359.0,237.0,287.0,382.0
15,Luxembourg,349.0,373.0,394.0,366.0,418.0,417.0,438.0,443.0,463.0,268.0,304.0,389.0
16,Hungary,7763.0,7769.0,7806.0,7710.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Malta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Netherlands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Austria,10172.0,10606.0,11188.0,11345.0,11433.0,12021.0,12077.0,12681.0,12761.0,6964.0,8054.0,12371.0
20,Poland,17633.0,17110.0,16453.0,15479.0,17024.0,18753.0,20120.0,20849.0,NaN,NaN,NaN,23646.0
21,Portugal,4237.0,3803.0,3649.0,3852.0,3957.0,4266.0,4516.0,4570.0,5055.0,2563.0,2912.0,4419.0
22,Romania,5044.0,4518.0,4352.0,4971.0,4910.0,4731.0,5556.0,5426.0,5735.0,3609.0,4104.0,5616.0
23,Slovenia,689.0,659.0,679.0,620.0,628.0,611.0,570.0,568.0,572.0,338.0,504.0,645.0
24,Slovakia,2431.0,2459.0,2485.0,2583.0,3411.0,3484.0,3754.0,3792.0,3957.0,2133.0,1969.0,3168.0
25,Finland,3882.0,4035.0,4053.0,3874.0,4114.0,3868.0,4271.0,4535.0,4924.0,2820.0,2903.0,4572.0
26,Sweden,11379.0,11792.0,11842.0,12121.0,12741.0,12800.0,13331.0,13547.0,14617.0,8129.0,8027.0,12879.0
27,Ieland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Liehtenstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Norway,3076.0,3092.0,3260.0,3440.0,3555.0,3695.0,3584.0,3722.0,3715.0,1801.0,1780.0,3079.0
30,Switzerland,18320.0,18115.0,18277.0,18801.0,19089.0,19573.0,19586.0,19245.0,20315.0,12419.0,13321.0,18022.0
31,United Kingdom,58462.0,60783.0,61950.0,64711.0,66594.0,68010.0,68912.0,69706.0,71823.0,NaN,NaN,NaN
32,Montenegro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,North Maedonia,145.0,99.0,80.0,80.0,177.0,83.0,59.0,63.0,62.0,25.0,25.0,46.0
34,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Türkiye,5882.0,4598.0,3775.0,4393.0,4828.0,4325.0,4566.0,5560.0,11068.0,6094.0,8544.0,NaN

In [9]:
# Function to get country code from country name
def get_country_code(df, country_name_column):
    def get_code(name):
        try:
            country = pycountry.countries.get(name=name)
            return country.alpha_3 if country else None
        except AttributeError:
            return None

    return df[country_name_column].apply(get_code)

# Add a new column 'Country Code' based on the get_country_code function
rail_df['Country Code'] = get_country_code(rail_df, 'Country Name')

# Move the 'Country Code' column to the second position
rail_df.insert(1, 'Country Code', rail_df.pop('Country Code'))

# Display the DataFrame with the new column
rail_df

,Country Name,Country Code,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Belgium,BEL,10498.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bulgaria,BGR,2059.0,1870.0,1821.0,1698.0,1549.0,1455.0,1434.0,1476.0,1520.0,1118.0,1203.0,1600.0
2,zehia,None,NaN,7196.0,7512.0,7644.0,8125.0,8738.0,9403.0,10220.0,10856.0,6623.0,6752.0,9394.0
3,Denmark,DNK,6395.0,6534.0,6566.0,6513.0,6507.0,6332.0,6280.0,6182.0,6174.0,3940.0,4181.0,6376.0
4,Germany,DEU,89316.0,93918.0,89450.0,90978.0,91050.0,95465.0,95529.0,98161.0,100252.0,57787.0,57518.0,92313.0
5,Estonia,EST,243.0,235.0,223.0,280.0,286.0,316.0,366.0,417.0,392.0,263.0,290.0,382.0
6,Ireland,IRL,1638.0,1578.0,1569.0,1728.0,1918.0,1991.0,2122.0,2281.0,2399.0,834.0,870.0,1748.0
7,Greee,None,958.0,832.0,1056.0,1072.0,1263.0,1192.0,1112.0,1104.0,1252.0,640.0,653.0,1117.0
8,Spain,ESP,22645.0,22170.0,23660.0,24915.0,26018.0,26532.0,27374.0,28317.0,28703.0,11987.0,17002.0,27489.0
9,Frane,None,91298.0,91205.0,90485.0,89499.0,91377.0,91832.0,95024.0,91818.0,96540.0,56606.0,75854.0,102814.0
10,roatia,None,1457.0,1080.0,935.0,917.0,941.0,827.0,736.0,747.0,724.0,448.0,538.0,812.0
11,Italy,ITA,45944.0,45753.0,47707.0,48881.0,51121.0,51716.0,52778.0,55037.0,56160.0,22064.0,27444.0,46143.0
12,yprus,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Latvia,LVA,733.0,717.0,721.0,644.0,590.0,584.0,596.0,624.0,643.0,413.0,361.0,541.0
14,Lithuania,LTU,269.0,278.0,278.0,270.0,262.0,280.0,315.0,354.0,359.0,237.0,287.0,382.0
15,Luxembourg,LUX,349.0,373.0,394.0,366.0,418.0,417.0,438.0,443.0,463.0,268.0,304.0,389.0
16,Hungary,HUN,7763.0,7769.0,7806.0,7710.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Malta,MLT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Netherlands,NLD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Austria,AUT,10172.0,10606.0,11188.0,11345.0,11433.0,12021.0,12077.0,12681.0,12761.0,6964.0,8054.0,12371.0
20,Poland,POL,17633.0,17110.0,16453.0,15479.0,17024.0,18753.0,20120.0,20849.0,NaN,NaN,NaN,23646.0
21,Portugal,PRT,4237.0,3803.0,3649.0,3852.0,3957.0,4266.0,4516.0,4570.0,5055.0,2563.0,2912.0,4419.0
22,Romania,ROU,5044.0,4518.0,4352.0,4971.0,4910.0,4731.0,5556.0,5426.0,5735.0,3609.0,4104.0,5616.0
23,Slovenia,SVN,689.0,659.0,679.0,620.0,628.0,611.0,570.0,568.0,572.0,338.0,504.0,645.0
24,Slovakia,SVK,2431.0,2459.0,2485.0,2583.0,3411.0,3484.0,3754.0,3792.0,3957.0,2133.0,1969.0,3168.0
25,Finland,FIN,3882.0,4035.0,4053.0,3874.0,4114.0,3868.0,4271.0,4535.0,4924.0,2820.0,2903.0,4572.0
26,Sweden,SWE,11379.0,11792.0,11842.0,12121.0,12741.0,12800.0,13331.0,13547.0,14617.0,8129.0,8027.0,12879.0
27,Ieland,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Liehtenstein,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Norway,NOR,3076.0,3092.0,3260.0,3440.0,3555.0,3695.0,3584.0,3722.0,3715.0,1801.0,1780.0,3079.0
30,Switzerland,CHE,18320.0,18115.0,18277.0,18801.0,19089.0,19573.0,19586.0,19245.0,20315.0,12419.0,13321.0,18022.0
31,United Kingdom,GBR,58462.0,60783.0,61950.0,64711.0,66594.0,68010.0,68912.0,69706.0,71823.0,NaN,NaN,NaN
32,Montenegro,MNE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,North Maedonia,None,145.0,99.0,80.0,80.0,177.0,83.0,59.0,63.0,62.0,25.0,25.0,46.0
34,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Serbia,SRB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Türkiye,TUR,5882.0,4598.0,3775.0,4393.0,4828.0,4325.0,4566.0,5560.0,11068.0,6094.0,8544.0,NaN

In [10]:
air_df = air_df.rename(columns={'Country': 'Country Name'})
air_df

,Country Name,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Belgium,25102695.0,25919515.0,26389927.0,28776258.0,30958841.0,30115832.0,33260493.0,34506309.0,35385188.0,9465828.0,13500020.0,27873892.0
1,Bulgaria,6652007.0,6819103.0,7079292.0,7520697.0,7610949.0,9324217.0,11092651.0,12137714.0,11713068.0,3729017.0,5047877.0,8807502.0
2,Czechia,12650532.0,11742352.0,11891812.0,12079873.0,12672004.0,13672362.0,16245554.0,17838221.0,18767088.0,3821372.0,4755160.0,11532650.0
3,Denmark,25808321.0,26532730.0,27459623.0,29015133.0,30095505.0,32763142.0,33261214.0,34701139.0,34780127.0,8658654.0,10817817.0,26649573.0
4,Germany,175316076.0,178591103.0,180783188.0,186445814.0,193936430.0,200687293.0,212389343.0,222422361.0,226764086.0,57795978.0,73597370.0,155302643.0
5,Estonia,1907569.0,2202427.0,1958565.0,2019806.0,2160978.0,2214989.0,2635145.0,2995528.0,3258003.0,857837.0,1292941.0,2731365.0
6,Ireland,23362889.0,23594089.0,24603640.0,26310826.0,29545020.0,32595709.0,34271771.0,36345005.0,37947510.0,8268297.0,9097359.0,32405890.0
7,Greece,33770739.0,32082336.0,34023934.0,39117833.0,42096402.0,45543371.0,50170728.0,54258826.0,56088527.0,17341192.0,32245559.0,57893929.0
8,Spain,165153230.0,159771261.0,157731973.0,165354382.0,174652503.0,193872037.0,209824089.0,220611429.0,228262372.0,57797305.0,91898241.0,199571203.0
9,France,126013257.0,129764462.0,132762875.0,136360671.0,140867569.0,145280602.0,154096485.0,161991179.0,168726788.0,50724011.0,66033809.0,136560938.0
10,Croatia,4989236.0,5422632.0,5722447.0,6140797.0,6571698.0,7475463.0,8843053.0,9731294.0,10623239.0,1943547.0,4458400.0,9415321.0
11,Italy,116226667.0,116029388.0,115279105.0,121164587.0,127665221.0,134477781.0,144306325.0,153352444.0,160667939.0,40405355.0,59709143.0,132425719.0
12,Cyprus,7190387.0,7328300.0,7011437.0,7328546.0,7590787.0,8961817.0,10238913.0,10927101.0,11261410.0,2270577.0,5099704.0,8613471.0
13,Latvia,5098360.0,4754530.0,4782257.0,4802282.0,5145856.0,5384160.0,6077854.0,7037070.0,7785726.0,1995133.0,2336134.0,5368369.0
14,Lithuania,2691991.0,3166628.0,3482358.0,3798110.0,4227389.0,4787561.0,5246101.0,6254178.0,6504685.0,1804500.0,2464603.0,5333890.0
15,Luxembourg,1836780.0,1893991.0,2169327.0,2433966.0,2651751.0,2984242.0,3554730.0,3988804.0,4365569.0,1426310.0,2002903.0,4057247.0
16,Hungary,8884837.0,8429843.0,8441319.0,9054848.0,10228352.0,11660366.0,13350029.0,15176493.0,16700750.0,3962687.0,4665369.0,12393512.0
17,Malta,3506814.0,3650347.0,4032029.0,4290032.0,4619557.0,5080446.0,6007731.0,6805817.0,7318357.0,1752445.0,2547912.0,5861597.0
18,Netherlands,53895292.0,55680209.0,58077271.0,60963003.0,64570938.0,70317995.0,76240304.0,79644163.0,81192507.0,23594783.0,29082583.0,61289771.0
19,Austria,25137612.0,25965977.0,25749724.0,26378676.0,26754007.0,27181511.0,28327279.0,31138417.0,35644188.0,9168431.0,11105564.0,26381180.0
20,Poland,20635672.0,21800765.0,23274484.0,25714422.0,28907439.0,32266861.0,37684668.0,43767548.0,46942771.0,13825460.0,18893812.0,39347542.0
21,Portugal,27579707.0,28186254.0,29694146.0,32560621.0,36005814.0,40930044.0,47673057.0,51018598.0,55007894.0,16548993.0,22347692.0,57081723.0
22,Romania,9687456.0,9674226.0,10016933.0,10907487.0,12580711.0,15153719.0,17934774.0,19809642.0,21565865.0,6633447.0,10384613.0,19535951.0
23,Slovenia,1358792.0,1167877.0,1265766.0,1307128.0,1436003.0,1404152.0,1682133.0,1810567.0,1719039.0,287787.0,419346.0,968811.0
24,Slovakia,1808187.0,1563197.0,1557149.0,1671290.0,1943656.0,2158261.0,2402651.0,2794094.0,2839787.0,500604.0,642078.0,1942568.0
25,Finland,16374398.0,16458815.0,16565391.0,17171931.0,17479246.0,18099954.0,20054947.0,22173530.0,23287929.0,5428622.0,4554497.0,13812577.0
26,Sweden,29732247.0,30350849.0,31443225.0,32766043.0,34011263.0,35952558.0,38456213.0,38945096.0,37614763.0,9317677.0,10798009.0,25038812.0
27,Iceland,2462894.0,2740691.0,3199266.0,3853614.0,4847288.0,6801814.0,8318734.0,10166386.0,7584197.0,1527633.0,2437139.0,6463479.0
28,Liechtenstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Norway,32403522.0,34592225.0,36686364.0,37603195.0,37503052.0,37727546.0,38739778.0,40030105.0,40348437.0,13216883.0,14136316.0,32562643.0
30,Switzerland,41439848.0,43236086.0,44217568.0,46127426.0,48026375.0,50505492.0,53564943.0,56139549.0,57194328.0,16006811.0,19109708.0,42424182.0
31,United Kingdom,201536753.0,203067015.0,210468980.0,220022122.0,232270437.0,248868873.0,264629454.0,272190155.0,277432380.0,NaN,NaN,NaN
32,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,987659.0,NaN
33,Montenegro,NaN,NaN,NaN,NaN,NaN,1845464.0,2173494.0,2440486.0,2652801.0,521959.0,1309266.0,1908552.0
34,North Macedonia,NaN,NaN,NaN,NaN,1452373.0,1649374.0,1861282.0,2152746.0,2353327.0,709241.0,1266230.0,2134988.0
35,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Serbia,NaN,NaN,NaN,NaN,NaN,4414858.0,4828171.0,5521250.0,6450643.0,1938468.0,3431750.0,5991693.0
37,Türkiye,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Add a new column 'Country Code' based on the get_country_code function
air_df['Country Code'] = get_country_code(air_df, 'Country Name')

# Move the 'Country Code' column to the second position
air_df.insert(1, 'Country Code', air_df.pop('Country Code'))

# Display the DataFrame with the new column
air_df

,Country Name,Country Code,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Belgium,BEL,25102695.0,25919515.0,26389927.0,28776258.0,30958841.0,30115832.0,33260493.0,34506309.0,35385188.0,9465828.0,13500020.0,27873892.0
1,Bulgaria,BGR,6652007.0,6819103.0,7079292.0,7520697.0,7610949.0,9324217.0,11092651.0,12137714.0,11713068.0,3729017.0,5047877.0,8807502.0
2,Czechia,CZE,12650532.0,11742352.0,11891812.0,12079873.0,12672004.0,13672362.0,16245554.0,17838221.0,18767088.0,3821372.0,4755160.0,11532650.0
3,Denmark,DNK,25808321.0,26532730.0,27459623.0,29015133.0,30095505.0,32763142.0,33261214.0,34701139.0,34780127.0,8658654.0,10817817.0,26649573.0
4,Germany,DEU,175316076.0,178591103.0,180783188.0,186445814.0,193936430.0,200687293.0,212389343.0,222422361.0,226764086.0,57795978.0,73597370.0,155302643.0
5,Estonia,EST,1907569.0,2202427.0,1958565.0,2019806.0,2160978.0,2214989.0,2635145.0,2995528.0,3258003.0,857837.0,1292941.0,2731365.0
6,Ireland,IRL,23362889.0,23594089.0,24603640.0,26310826.0,29545020.0,32595709.0,34271771.0,36345005.0,37947510.0,8268297.0,9097359.0,32405890.0
7,Greece,GRC,33770739.0,32082336.0,34023934.0,39117833.0,42096402.0,45543371.0,50170728.0,54258826.0,56088527.0,17341192.0,32245559.0,57893929.0
8,Spain,ESP,165153230.0,159771261.0,157731973.0,165354382.0,174652503.0,193872037.0,209824089.0,220611429.0,228262372.0,57797305.0,91898241.0,199571203.0
9,France,FRA,126013257.0,129764462.0,132762875.0,136360671.0,140867569.0,145280602.0,154096485.0,161991179.0,168726788.0,50724011.0,66033809.0,136560938.0
10,Croatia,HRV,4989236.0,5422632.0,5722447.0,6140797.0,6571698.0,7475463.0,8843053.0,9731294.0,10623239.0,1943547.0,4458400.0,9415321.0
11,Italy,ITA,116226667.0,116029388.0,115279105.0,121164587.0,127665221.0,134477781.0,144306325.0,153352444.0,160667939.0,40405355.0,59709143.0,132425719.0
12,Cyprus,CYP,7190387.0,7328300.0,7011437.0,7328546.0,7590787.0,8961817.0,10238913.0,10927101.0,11261410.0,2270577.0,5099704.0,8613471.0
13,Latvia,LVA,5098360.0,4754530.0,4782257.0,4802282.0,5145856.0,5384160.0,6077854.0,7037070.0,7785726.0,1995133.0,2336134.0,5368369.0
14,Lithuania,LTU,2691991.0,3166628.0,3482358.0,3798110.0,4227389.0,4787561.0,5246101.0,6254178.0,6504685.0,1804500.0,2464603.0,5333890.0
15,Luxembourg,LUX,1836780.0,1893991.0,2169327.0,2433966.0,2651751.0,2984242.0,3554730.0,3988804.0,4365569.0,1426310.0,2002903.0,4057247.0
16,Hungary,HUN,8884837.0,8429843.0,8441319.0,9054848.0,10228352.0,11660366.0,13350029.0,15176493.0,16700750.0,3962687.0,4665369.0,12393512.0
17,Malta,MLT,3506814.0,3650347.0,4032029.0,4290032.0,4619557.0,5080446.0,6007731.0,6805817.0,7318357.0,1752445.0,2547912.0,5861597.0
18,Netherlands,NLD,53895292.0,55680209.0,58077271.0,60963003.0,64570938.0,70317995.0,76240304.0,79644163.0,81192507.0,23594783.0,29082583.0,61289771.0
19,Austria,AUT,25137612.0,25965977.0,25749724.0,26378676.0,26754007.0,27181511.0,28327279.0,31138417.0,35644188.0,9168431.0,11105564.0,26381180.0
20,Poland,POL,20635672.0,21800765.0,23274484.0,25714422.0,28907439.0,32266861.0,37684668.0,43767548.0,46942771.0,13825460.0,18893812.0,39347542.0
21,Portugal,PRT,27579707.0,28186254.0,29694146.0,32560621.0,36005814.0,40930044.0,47673057.0,51018598.0,55007894.0,16548993.0,22347692.0,57081723.0
22,Romania,ROU,9687456.0,9674226.0,10016933.0,10907487.0,12580711.0,15153719.0,17934774.0,19809642.0,21565865.0,6633447.0,10384613.0,19535951.0
23,Slovenia,SVN,1358792.0,1167877.0,1265766.0,1307128.0,1436003.0,1404152.0,1682133.0,1810567.0,1719039.0,287787.0,419346.0,968811.0
24,Slovakia,SVK,1808187.0,1563197.0,1557149.0,1671290.0,1943656.0,2158261.0,2402651.0,2794094.0,2839787.0,500604.0,642078.0,1942568.0
25,Finland,FIN,16374398.0,16458815.0,16565391.0,17171931.0,17479246.0,18099954.0,20054947.0,22173530.0,23287929.0,5428622.0,4554497.0,13812577.0
26,Sweden,SWE,29732247.0,30350849.0,31443225.0,32766043.0,34011263.0,35952558.0,38456213.0,38945096.0,37614763.0,9317677.0,10798009.0,25038812.0
27,Iceland,ISL,2462894.0,2740691.0,3199266.0,3853614.0,4847288.0,6801814.0,8318734.0,10166386.0,7584197.0,1527633.0,2437139.0,6463479.0
28,Liechtenstein,LIE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Norway,NOR,32403522.0,34592225.0,36686364.0,37603195.0,37503052.0,37727546.0,38739778.0,40030105.0,40348437.0,13216883.0,14136316.0,32562643.0
30,Switzerland,CHE,41439848.0,43236086.0,44217568.0,46127426.0,48026375.0,50505492.0,53564943.0,56139549.0,57194328.0,16006811.0,19109708.0,42424182.0
31,United Kingdom,GBR,201536753.0,203067015.0,210468980.0,220022122.0,232270437.0,248868873.0,264629454.0,272190155.0,277432380.0,NaN,NaN,NaN
32,Bosnia and Herzegovina,BIH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,987659.0,NaN
33,Montenegro,MNE,NaN,NaN,NaN,NaN,NaN,1845464.0,2173494.0,2440486.0,2652801.0,521959.0,1309266.0,1908552.0
34,North Macedonia,MKD,NaN,NaN,NaN,NaN,1452373.0,1649374.0,1861282.0,2152746.0,2353327.0,709241.0,1266230.0,2134988.0
35,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Serbia,SRB,NaN,NaN,NaN,NaN,NaN,4414858.0,4828171.0,5521250.0,6450643.0,1938468.0,3431750.0,5991693.0
37,Türkiye,TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Sort air_df by 'Country Name'
air_df = air_df.sort_values(by='Country Name', ascending=True)

air_df

,Country Name,Country Code,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
35,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Austria,AUT,25137612.0,25965977.0,25749724.0,26378676.0,26754007.0,27181511.0,28327279.0,31138417.0,35644188.0,9168431.0,11105564.0,26381180.0
0,Belgium,BEL,25102695.0,25919515.0,26389927.0,28776258.0,30958841.0,30115832.0,33260493.0,34506309.0,35385188.0,9465828.0,13500020.0,27873892.0
32,Bosnia and Herzegovina,BIH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,987659.0,NaN
1,Bulgaria,BGR,6652007.0,6819103.0,7079292.0,7520697.0,7610949.0,9324217.0,11092651.0,12137714.0,11713068.0,3729017.0,5047877.0,8807502.0
10,Croatia,HRV,4989236.0,5422632.0,5722447.0,6140797.0,6571698.0,7475463.0,8843053.0,9731294.0,10623239.0,1943547.0,4458400.0,9415321.0
12,Cyprus,CYP,7190387.0,7328300.0,7011437.0,7328546.0,7590787.0,8961817.0,10238913.0,10927101.0,11261410.0,2270577.0,5099704.0,8613471.0
2,Czechia,CZE,12650532.0,11742352.0,11891812.0,12079873.0,12672004.0,13672362.0,16245554.0,17838221.0,18767088.0,3821372.0,4755160.0,11532650.0
3,Denmark,DNK,25808321.0,26532730.0,27459623.0,29015133.0,30095505.0,32763142.0,33261214.0,34701139.0,34780127.0,8658654.0,10817817.0,26649573.0
5,Estonia,EST,1907569.0,2202427.0,1958565.0,2019806.0,2160978.0,2214989.0,2635145.0,2995528.0,3258003.0,857837.0,1292941.0,2731365.0
25,Finland,FIN,16374398.0,16458815.0,16565391.0,17171931.0,17479246.0,18099954.0,20054947.0,22173530.0,23287929.0,5428622.0,4554497.0,13812577.0
9,France,FRA,126013257.0,129764462.0,132762875.0,136360671.0,140867569.0,145280602.0,154096485.0,161991179.0,168726788.0,50724011.0,66033809.0,136560938.0
4,Germany,DEU,175316076.0,178591103.0,180783188.0,186445814.0,193936430.0,200687293.0,212389343.0,222422361.0,226764086.0,57795978.0,73597370.0,155302643.0
7,Greece,GRC,33770739.0,32082336.0,34023934.0,39117833.0,42096402.0,45543371.0,50170728.0,54258826.0,56088527.0,17341192.0,32245559.0,57893929.0
16,Hungary,HUN,8884837.0,8429843.0,8441319.0,9054848.0,10228352.0,11660366.0,13350029.0,15176493.0,16700750.0,3962687.0,4665369.0,12393512.0
27,Iceland,ISL,2462894.0,2740691.0,3199266.0,3853614.0,4847288.0,6801814.0,8318734.0,10166386.0,7584197.0,1527633.0,2437139.0,6463479.0
6,Ireland,IRL,23362889.0,23594089.0,24603640.0,26310826.0,29545020.0,32595709.0,34271771.0,36345005.0,37947510.0,8268297.0,9097359.0,32405890.0
11,Italy,ITA,116226667.0,116029388.0,115279105.0,121164587.0,127665221.0,134477781.0,144306325.0,153352444.0,160667939.0,40405355.0,59709143.0,132425719.0
13,Latvia,LVA,5098360.0,4754530.0,4782257.0,4802282.0,5145856.0,5384160.0,6077854.0,7037070.0,7785726.0,1995133.0,2336134.0,5368369.0
28,Liechtenstein,LIE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Lithuania,LTU,2691991.0,3166628.0,3482358.0,3798110.0,4227389.0,4787561.0,5246101.0,6254178.0,6504685.0,1804500.0,2464603.0,5333890.0
15,Luxembourg,LUX,1836780.0,1893991.0,2169327.0,2433966.0,2651751.0,2984242.0,3554730.0,3988804.0,4365569.0,1426310.0,2002903.0,4057247.0
17,Malta,MLT,3506814.0,3650347.0,4032029.0,4290032.0,4619557.0,5080446.0,6007731.0,6805817.0,7318357.0,1752445.0,2547912.0,5861597.0
33,Montenegro,MNE,NaN,NaN,NaN,NaN,NaN,1845464.0,2173494.0,2440486.0,2652801.0,521959.0,1309266.0,1908552.0
18,Netherlands,NLD,53895292.0,55680209.0,58077271.0,60963003.0,64570938.0,70317995.0,76240304.0,79644163.0,81192507.0,23594783.0,29082583.0,61289771.0
34,North Macedonia,MKD,NaN,NaN,NaN,NaN,1452373.0,1649374.0,1861282.0,2152746.0,2353327.0,709241.0,1266230.0,2134988.0
29,Norway,NOR,32403522.0,34592225.0,36686364.0,37603195.0,37503052.0,37727546.0,38739778.0,40030105.0,40348437.0,13216883.0,14136316.0,32562643.0
20,Poland,POL,20635672.0,21800765.0,23274484.0,25714422.0,28907439.0,32266861.0,37684668.0,43767548.0,46942771.0,13825460.0,18893812.0,39347542.0
21,Portugal,PRT,27579707.0,28186254.0,29694146.0,32560621.0,36005814.0,40930044.0,47673057.0,51018598.0,55007894.0,16548993.0,22347692.0,57081723.0
22,Romania,ROU,9687456.0,9674226.0,10016933.0,10907487.0,12580711.0,15153719.0,17934774.0,19809642.0,21565865.0,6633447.0,10384613.0,19535951.0
36,Serbia,SRB,NaN,NaN,NaN,NaN,NaN,4414858.0,4828171.0,5521250.0,6450643.0,1938468.0,3431750.0,5991693.0
24,Slovakia,SVK,1808187.0,1563197.0,1557149.0,1671290.0,1943656.0,2158261.0,2402651.0,2794094.0,2839787.0,500604.0,642078.0,1942568.0
23,Slovenia,SVN,1358792.0,1167877.0,1265766.0,1307128.0,1436003.0,1404152.0,1682133.0,1810567.0,1719039.0,287787.0,419346.0,968811.0
8,Spain,ESP,165153230.0,159771261.0,157731973.0,165354382.0,174652503.0,193872037.0,209824089.0,220611429.0,228262372.0,57797305.0,91898241.0,199571203.0
26,Sweden,SWE,29732247.0,30350849.0,31443225.0,32766043.0,34011263.0,35952558.0,38456213.0,38945096.0,37614763.0,9317677.0,10798009.0,25038812.0
30,Switzerland,CHE,41439848.0,43236086.0,44217568.0,46127426.0,48026375.0,50505492.0,53564943.0,56139549.0,57194328.0,16006811.0,19109708.0,42424182.0
37,Türkiye,TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,United Kingdom,GBR,201536753.0,203067015.0,210468980.0,220022122.0,232270437.0,248868873.0,264629454.0,272190155.0,277432380.0,NaN,NaN,NaN

In [13]:
# Sort rail_df by 'Country Name'
rail_df = rail_df.sort_values(by='Country Name', ascending=True)
rail_df

,Country Name,Country Code,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
34,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Austria,AUT,10172.0,10606.0,11188.0,11345.0,11433.0,12021.0,12077.0,12681.0,12761.0,6964.0,8054.0,12371.0
0,Belgium,BEL,10498.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bulgaria,BGR,2059.0,1870.0,1821.0,1698.0,1549.0,1455.0,1434.0,1476.0,1520.0,1118.0,1203.0,1600.0
3,Denmark,DNK,6395.0,6534.0,6566.0,6513.0,6507.0,6332.0,6280.0,6182.0,6174.0,3940.0,4181.0,6376.0
5,Estonia,EST,243.0,235.0,223.0,280.0,286.0,316.0,366.0,417.0,392.0,263.0,290.0,382.0
25,Finland,FIN,3882.0,4035.0,4053.0,3874.0,4114.0,3868.0,4271.0,4535.0,4924.0,2820.0,2903.0,4572.0
9,Frane,None,91298.0,91205.0,90485.0,89499.0,91377.0,91832.0,95024.0,91818.0,96540.0,56606.0,75854.0,102814.0
4,Germany,DEU,89316.0,93918.0,89450.0,90978.0,91050.0,95465.0,95529.0,98161.0,100252.0,57787.0,57518.0,92313.0
7,Greee,None,958.0,832.0,1056.0,1072.0,1263.0,1192.0,1112.0,1104.0,1252.0,640.0,653.0,1117.0
16,Hungary,HUN,7763.0,7769.0,7806.0,7710.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Ieland,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Ireland,IRL,1638.0,1578.0,1569.0,1728.0,1918.0,1991.0,2122.0,2281.0,2399.0,834.0,870.0,1748.0
11,Italy,ITA,45944.0,45753.0,47707.0,48881.0,51121.0,51716.0,52778.0,55037.0,56160.0,22064.0,27444.0,46143.0
13,Latvia,LVA,733.0,717.0,721.0,644.0,590.0,584.0,596.0,624.0,643.0,413.0,361.0,541.0
28,Liehtenstein,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Lithuania,LTU,269.0,278.0,278.0,270.0,262.0,280.0,315.0,354.0,359.0,237.0,287.0,382.0
15,Luxembourg,LUX,349.0,373.0,394.0,366.0,418.0,417.0,438.0,443.0,463.0,268.0,304.0,389.0
17,Malta,MLT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Montenegro,MNE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Netherlands,NLD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,North Maedonia,None,145.0,99.0,80.0,80.0,177.0,83.0,59.0,63.0,62.0,25.0,25.0,46.0
29,Norway,NOR,3076.0,3092.0,3260.0,3440.0,3555.0,3695.0,3584.0,3722.0,3715.0,1801.0,1780.0,3079.0
20,Poland,POL,17633.0,17110.0,16453.0,15479.0,17024.0,18753.0,20120.0,20849.0,NaN,NaN,NaN,23646.0
21,Portugal,PRT,4237.0,3803.0,3649.0,3852.0,3957.0,4266.0,4516.0,4570.0,5055.0,2563.0,2912.0,4419.0
22,Romania,ROU,5044.0,4518.0,4352.0,4971.0,4910.0,4731.0,5556.0,5426.0,5735.0,3609.0,4104.0,5616.0
35,Serbia,SRB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Slovakia,SVK,2431.0,2459.0,2485.0,2583.0,3411.0,3484.0,3754.0,3792.0,3957.0,2133.0,1969.0,3168.0
23,Slovenia,SVN,689.0,659.0,679.0,620.0,628.0,611.0,570.0,568.0,572.0,338.0,504.0,645.0
8,Spain,ESP,22645.0,22170.0,23660.0,24915.0,26018.0,26532.0,27374.0,28317.0,28703.0,11987.0,17002.0,27489.0
26,Sweden,SWE,11379.0,11792.0,11842.0,12121.0,12741.0,12800.0,13331.0,13547.0,14617.0,8129.0,8027.0,12879.0
30,Switzerland,CHE,18320.0,18115.0,18277.0,18801.0,19089.0,19573.0,19586.0,19245.0,20315.0,12419.0,13321.0,18022.0
36,Türkiye,TUR,5882.0,4598.0,3775.0,4393.0,4828.0,4325.0,4566.0,5560.0,11068.0,6094.0,8544.0,NaN
31,United Kingdom,GBR,58462.0,60783.0,61950.0,64711.0,66594.0,68010.0,68912.0,69706.0,71823.0,NaN,NaN,NaN
10,roatia,None,1457.0,1080.0,935.0,917.0,941.0,827.0,736.0,747.0,724.0,448.0,538.0,812.0
12,yprus,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,zehia,None,NaN,7196.0,7512.0,7644.0,8125.0,8738.0,9403.0,10220.0,10856.0,6623.0,6752.0,9394.0

In [14]:
country_name_mapping = {
    'Frane': 'France',
    'Greee': 'Greece',
    'Liehtenstein': 'Liechtenstein',
    'North Maedonia': 'North Macedonia',
    'roatia': 'Croatia',
    'yprus': 'Cyprus',
    'zehia': 'Czechia',
    'Ieland': 'Iceland'
}

# Replace values in the 'Country Name' column
rail_df['Country Name'] = rail_df['Country Name'].replace(country_name_mapping)

# Display the DataFrame with updated values
rail_df

,Country Name,Country Code,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
34,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Austria,AUT,10172.0,10606.0,11188.0,11345.0,11433.0,12021.0,12077.0,12681.0,12761.0,6964.0,8054.0,12371.0
0,Belgium,BEL,10498.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bulgaria,BGR,2059.0,1870.0,1821.0,1698.0,1549.0,1455.0,1434.0,1476.0,1520.0,1118.0,1203.0,1600.0
3,Denmark,DNK,6395.0,6534.0,6566.0,6513.0,6507.0,6332.0,6280.0,6182.0,6174.0,3940.0,4181.0,6376.0
5,Estonia,EST,243.0,235.0,223.0,280.0,286.0,316.0,366.0,417.0,392.0,263.0,290.0,382.0
25,Finland,FIN,3882.0,4035.0,4053.0,3874.0,4114.0,3868.0,4271.0,4535.0,4924.0,2820.0,2903.0,4572.0
9,France,None,91298.0,91205.0,90485.0,89499.0,91377.0,91832.0,95024.0,91818.0,96540.0,56606.0,75854.0,102814.0
4,Germany,DEU,89316.0,93918.0,89450.0,90978.0,91050.0,95465.0,95529.0,98161.0,100252.0,57787.0,57518.0,92313.0
7,Greece,None,958.0,832.0,1056.0,1072.0,1263.0,1192.0,1112.0,1104.0,1252.0,640.0,653.0,1117.0
16,Hungary,HUN,7763.0,7769.0,7806.0,7710.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Iceland,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Ireland,IRL,1638.0,1578.0,1569.0,1728.0,1918.0,1991.0,2122.0,2281.0,2399.0,834.0,870.0,1748.0
11,Italy,ITA,45944.0,45753.0,47707.0,48881.0,51121.0,51716.0,52778.0,55037.0,56160.0,22064.0,27444.0,46143.0
13,Latvia,LVA,733.0,717.0,721.0,644.0,590.0,584.0,596.0,624.0,643.0,413.0,361.0,541.0
28,Liechtenstein,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Lithuania,LTU,269.0,278.0,278.0,270.0,262.0,280.0,315.0,354.0,359.0,237.0,287.0,382.0
15,Luxembourg,LUX,349.0,373.0,394.0,366.0,418.0,417.0,438.0,443.0,463.0,268.0,304.0,389.0
17,Malta,MLT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Montenegro,MNE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Netherlands,NLD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,North Macedonia,None,145.0,99.0,80.0,80.0,177.0,83.0,59.0,63.0,62.0,25.0,25.0,46.0
29,Norway,NOR,3076.0,3092.0,3260.0,3440.0,3555.0,3695.0,3584.0,3722.0,3715.0,1801.0,1780.0,3079.0
20,Poland,POL,17633.0,17110.0,16453.0,15479.0,17024.0,18753.0,20120.0,20849.0,NaN,NaN,NaN,23646.0
21,Portugal,PRT,4237.0,3803.0,3649.0,3852.0,3957.0,4266.0,4516.0,4570.0,5055.0,2563.0,2912.0,4419.0
22,Romania,ROU,5044.0,4518.0,4352.0,4971.0,4910.0,4731.0,5556.0,5426.0,5735.0,3609.0,4104.0,5616.0
35,Serbia,SRB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Slovakia,SVK,2431.0,2459.0,2485.0,2583.0,3411.0,3484.0,3754.0,3792.0,3957.0,2133.0,1969.0,3168.0
23,Slovenia,SVN,689.0,659.0,679.0,620.0,628.0,611.0,570.0,568.0,572.0,338.0,504.0,645.0
8,Spain,ESP,22645.0,22170.0,23660.0,24915.0,26018.0,26532.0,27374.0,28317.0,28703.0,11987.0,17002.0,27489.0
26,Sweden,SWE,11379.0,11792.0,11842.0,12121.0,12741.0,12800.0,13331.0,13547.0,14617.0,8129.0,8027.0,12879.0
30,Switzerland,CHE,18320.0,18115.0,18277.0,18801.0,19089.0,19573.0,19586.0,19245.0,20315.0,12419.0,13321.0,18022.0
36,Türkiye,TUR,5882.0,4598.0,3775.0,4393.0,4828.0,4325.0,4566.0,5560.0,11068.0,6094.0,8544.0,NaN
31,United Kingdom,GBR,58462.0,60783.0,61950.0,64711.0,66594.0,68010.0,68912.0,69706.0,71823.0,NaN,NaN,NaN
10,Croatia,None,1457.0,1080.0,935.0,917.0,941.0,827.0,736.0,747.0,724.0,448.0,538.0,812.0
12,Cyprus,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Czechia,None,NaN,7196.0,7512.0,7644.0,8125.0,8738.0,9403.0,10220.0,10856.0,6623.0,6752.0,9394.0

In [15]:
# Add a new column 'Country Code' based on the get_country_code function
rail_df['Country Code'] = get_country_code(rail_df, 'Country Name')

# Move the 'Country Code' column to the second position
rail_df.insert(1, 'Country Code', rail_df.pop('Country Code'))

# Display the DataFrame with the new column
rail_df

,Country Name,Country Code,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
34,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Austria,AUT,10172.0,10606.0,11188.0,11345.0,11433.0,12021.0,12077.0,12681.0,12761.0,6964.0,8054.0,12371.0
0,Belgium,BEL,10498.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bulgaria,BGR,2059.0,1870.0,1821.0,1698.0,1549.0,1455.0,1434.0,1476.0,1520.0,1118.0,1203.0,1600.0
3,Denmark,DNK,6395.0,6534.0,6566.0,6513.0,6507.0,6332.0,6280.0,6182.0,6174.0,3940.0,4181.0,6376.0
5,Estonia,EST,243.0,235.0,223.0,280.0,286.0,316.0,366.0,417.0,392.0,263.0,290.0,382.0
25,Finland,FIN,3882.0,4035.0,4053.0,3874.0,4114.0,3868.0,4271.0,4535.0,4924.0,2820.0,2903.0,4572.0
9,France,FRA,91298.0,91205.0,90485.0,89499.0,91377.0,91832.0,95024.0,91818.0,96540.0,56606.0,75854.0,102814.0
4,Germany,DEU,89316.0,93918.0,89450.0,90978.0,91050.0,95465.0,95529.0,98161.0,100252.0,57787.0,57518.0,92313.0
7,Greece,GRC,958.0,832.0,1056.0,1072.0,1263.0,1192.0,1112.0,1104.0,1252.0,640.0,653.0,1117.0
16,Hungary,HUN,7763.0,7769.0,7806.0,7710.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Iceland,ISL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Ireland,IRL,1638.0,1578.0,1569.0,1728.0,1918.0,1991.0,2122.0,2281.0,2399.0,834.0,870.0,1748.0
11,Italy,ITA,45944.0,45753.0,47707.0,48881.0,51121.0,51716.0,52778.0,55037.0,56160.0,22064.0,27444.0,46143.0
13,Latvia,LVA,733.0,717.0,721.0,644.0,590.0,584.0,596.0,624.0,643.0,413.0,361.0,541.0
28,Liechtenstein,LIE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Lithuania,LTU,269.0,278.0,278.0,270.0,262.0,280.0,315.0,354.0,359.0,237.0,287.0,382.0
15,Luxembourg,LUX,349.0,373.0,394.0,366.0,418.0,417.0,438.0,443.0,463.0,268.0,304.0,389.0
17,Malta,MLT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Montenegro,MNE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Netherlands,NLD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,North Macedonia,MKD,145.0,99.0,80.0,80.0,177.0,83.0,59.0,63.0,62.0,25.0,25.0,46.0
29,Norway,NOR,3076.0,3092.0,3260.0,3440.0,3555.0,3695.0,3584.0,3722.0,3715.0,1801.0,1780.0,3079.0
20,Poland,POL,17633.0,17110.0,16453.0,15479.0,17024.0,18753.0,20120.0,20849.0,NaN,NaN,NaN,23646.0
21,Portugal,PRT,4237.0,3803.0,3649.0,3852.0,3957.0,4266.0,4516.0,4570.0,5055.0,2563.0,2912.0,4419.0
22,Romania,ROU,5044.0,4518.0,4352.0,4971.0,4910.0,4731.0,5556.0,5426.0,5735.0,3609.0,4104.0,5616.0
35,Serbia,SRB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Slovakia,SVK,2431.0,2459.0,2485.0,2583.0,3411.0,3484.0,3754.0,3792.0,3957.0,2133.0,1969.0,3168.0
23,Slovenia,SVN,689.0,659.0,679.0,620.0,628.0,611.0,570.0,568.0,572.0,338.0,504.0,645.0
8,Spain,ESP,22645.0,22170.0,23660.0,24915.0,26018.0,26532.0,27374.0,28317.0,28703.0,11987.0,17002.0,27489.0
26,Sweden,SWE,11379.0,11792.0,11842.0,12121.0,12741.0,12800.0,13331.0,13547.0,14617.0,8129.0,8027.0,12879.0
30,Switzerland,CHE,18320.0,18115.0,18277.0,18801.0,19089.0,19573.0,19586.0,19245.0,20315.0,12419.0,13321.0,18022.0
36,Türkiye,TUR,5882.0,4598.0,3775.0,4393.0,4828.0,4325.0,4566.0,5560.0,11068.0,6094.0,8544.0,NaN
31,United Kingdom,GBR,58462.0,60783.0,61950.0,64711.0,66594.0,68010.0,68912.0,69706.0,71823.0,NaN,NaN,NaN
10,Croatia,HRV,1457.0,1080.0,935.0,917.0,941.0,827.0,736.0,747.0,724.0,448.0,538.0,812.0
12,Cyprus,CYP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Czechia,CZE,NaN,7196.0,7512.0,7644.0,8125.0,8738.0,9403.0,10220.0,10856.0,6623.0,6752.0,9394.0

In [16]:
# Extract unique country codes from rail_df
valid_country_codes = rail_df['Country Code'].unique()

# Filter population_df and income_df based on valid country codes
population_df = population_df[population_df['Country Code'].isin(valid_country_codes)]
# Display the filtered DataFrames
population_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
5,Albania,ALB,"Population, total",SP.POP.TOTL,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,...,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0,2866376.0,2854191.0,2837849.0,2811666.0,2777689.0
14,Austria,AUT,"Population, total",SP.POP.TOTL,7047539.0,7086299.0,7129864.0,7175811.0,7223801.0,7270889.0,...,8479823.0,8546356.0,8642699.0,8736668.0,8797566.0,8840521.0,8879920.0,8916864.0,8955797.0,9041851.0
17,Belgium,BEL,"Population, total",SP.POP.TOTL,9153489.0,9183948.0,9220578.0,9289770.0,9378113.0,9463667.0,...,11159407.0,11209057.0,11274196.0,11331422.0,11375158.0,11427054.0,11488980.0,11538604.0,11586195.0,11685814.0
21,Bulgaria,BGR,"Population, total",SP.POP.TOTL,7867374.0,7943118.0,8012946.0,8078145.0,8144340.0,8204168.0,...,7265115.0,7223938.0,7177991.0,7127822.0,7075947.0,7025037.0,6975761.0,6934015.0,6877743.0,6465097.0
37,Switzerland,CHE,"Population, total",SP.POP.TOTL,5327827.0,5434294.0,5573815.0,5694247.0,5789228.0,5856472.0,...,8089346.0,8188649.0,8282396.0,8373338.0,8451840.0,8514329.0,8575280.0,8638167.0,8704546.0,8775760.0
53,Cyprus,CYP,"Population, total",SP.POP.TOTL,585725.0,594771.0,601095.0,607072.0,612338.0,617345.0,...,1166968.0,1176995.0,1187280.0,1197881.0,1208523.0,1218831.0,1228836.0,1237537.0,1244188.0,1251488.0
54,Czechia,CZE,"Population, total",SP.POP.TOTL,9602006.0,9586651.0,9624660.0,9670685.0,9727804.0,9779358.0,...,10514272.0,10525347.0,10546059.0,10566332.0,10594438.0,10629928.0,10671870.0,10697858.0,10505772.0,10672118.0
55,Germany,DEU,"Population, total",SP.POP.TOTL,72814900.0,73377632.0,74025784.0,74714353.0,75318337.0,75963695.0,...,80645605.0,80982500.0,81686611.0,82348669.0,82657002.0,82905782.0,83092962.0,83160871.0,83196078.0,83797985.0
58,Denmark,DNK,"Population, total",SP.POP.TOTL,4579603.0,4611687.0,4647727.0,4684483.0,4722072.0,4759012.0,...,5614932.0,5643475.0,5683483.0,5728010.0,5764980.0,5793636.0,5814422.0,5831404.0,5856733.0,5903037.0
70,Spain,ESP,"Population, total",SP.POP.TOTL,30455000.0,30739250.0,31023366.0,31296651.0,31609195.0,31954292.0,...,46620045.0,46480882.0,46444832.0,46484062.0,46593236.0,46797754.0,47134837.0,47365655.0,47415794.0,47778340.0
71,Estonia,EST,"Population, total",SP.POP.TOTL,1211537.0,1225077.0,1241623.0,1258857.0,1277086.0,1294566.0,...,1317997.0,1314545.0,1315407.0,1315790.0,1317384.0,1321977.0,1326898.0,1329522.0,1330932.0,1348840.0
75,Finland,FIN,"Population, total",SP.POP.TOTL,4429634.0,4461005.0,4491443.0,4523309.0,4548543.0,4563732.0,...,5438972.0,5461512.0,5479531.0,5495303.0,5508214.0,5515525.0,5521606.0,5529543.0,5541017.0,5556106.0
77,France,FRA,"Population, total",SP.POP.TOTL,46649927.0,47161641.0,47679792.0,48189939.0,48733997.0,49282756.0,...,66002289.0,66312067.0,66548272.0,66724104.0,66918020.0,67158348.0,67388001.0,67571107.0,67764304.0,67971311.0
81,United Kingdom,GBR,"Population, total",SP.POP.TOTL,52400000.0,52800000.0,53250000.0,53650000.0,54000000.0,54348050.0,...,64128273.0,64602298.0,65116219.0,65611593.0,66058859.0,66460344.0,66836327.0,67081234.0,67026292.0,66971395.0
89,Greece,GRC,"Population, total",SP.POP.TOTL,8331725.0,8398050.0,8448233.0,8479625.0,8510429.0,8550333.0,...,10965211.0,10892413.0,10820883.0,10775971.0,10754679.0,10732882.0,10721582.0,10698599.0,10569207.0,10426919.0
99,Croatia,HRV,"Population, total",SP.POP.TOTL,4140181.0,4167292.0,4196712.0,4225675.0,4252876.0,4280923.0,...,4255689.0,4238389.0,4203604.0,4174349.0,4124531.0,4087843.0,4065253.0,4047680.0,3879000.0,3855600.0
101,Hungary,HUN,"Population, total",SP.POP.TOTL,9983967.0,10029321.0,10061734.0,10087947.0,10119835.0,10147935.0,...,9893082.0,9866468.0,9843028.0,9814023.0,9787966.0,9775564.0,9771141.0,9750149.0,9709891.0,9643048.0
111,Ireland,IRL,"Population, total",SP.POP.TOTL,2828600.0,2824400.0,2836050.0,2852650.0,2866550.0,2877300.0,...,4623816.0,4657740.0,4701957.0,4755335.0,4807388.0,4867316.0,4934340.0,4985382.0,5033164.0,5127170.0
114,Iceland,ISL,"Population, total",SP.POP.TOTL,175574.0,179029.0,182378.0,185653.0,188983.0,192286.0,...,323764.0,327386.0,330815.0,335439.0,343400.0,352721.0,360563.0,366463.0,372520.0,382003.0
116,Italy,ITA,"Population, total",SP.POP.TOTL,50199700.0,50536350.0,50879450.0,51252000.0,51675350.0,52112350.0,...,60233948.0,60789140.0,60730582.0,60627498.0,60536709.0,60421760.0,59729081.0,59438851.0,59133173.0,58940425.0
137,Liechtenstein,LIE,"Population, total",SP.POP.TOTL,16472.0,16834.0,17221.0,17625.0,18058.0,18500.0,...,36806.0,37096.0,37355.0,37609.0,37889.0,38181.0,38482.0,38756.0,39039.0,39327.0
143,Lithuania,LTU,"Population, total",SP.POP.TOTL,2778550.0,2823550.0,2863350.0,2898950.0,2935200.0,2971450.0,...,2957689.0,2932367.0,2904910.0,2868231.0,2828403.0,2801543.0,2794137.0,2794885.0,2800839.0,2831639.0
144,Luxembourg,LUX,"Population, total",SP.POP.TOTL,313970.0,316845.0,320750.0,324100.0,327750.0,331500.0,...,543360.0,556319.0,569604.0,582014.0,596336.0,607950.0,620001.0,630419.0,640064.0,653103.0
145,Latvia,LVA,"Population, total",SP.POP.TOTL,2120979.0,2152681.0,2181586.0,2210919.0,2240623.0,2265919.0,...,2012647.0,1993782.0,1977527.0,1959537.0,1942248.0,1927174.0,1913822.0,1900449.0,1884490.0,1879383.0
157,North Macedonia,MKD,"Population, total",SP.POP.TOTL,1462368.0,1481112.0,1497338.0,1511854.0,1529507.0,1547982.0,...,2064032.0,2067471.0,2070226.0,2072490.0,2074502.0,2076217.0,2076694.0,2072531.0,2065092.0,2057679.0
159,Malta,MLT,"Population, total",SP.POP.TOTL,326550.0,325250.0,323900.0,322550.0,321250.0,318800.0,...,425967.0,434558.0,445053.0,455356.0,467999.0,484630.0,504062.0,515332.0,518536.0,531113.0
162,Montenegro,MNE,"Population, total",SP.POP.TOTL,480579.0,491140.0,502558.0,513409.0,521753.0,526327.0,...,621207.0,621810.0,622159.0,622303.0,622373.0,622227.0,622028.0,621306.0,619211.0,617213.0
176,Netherlands,NLD,"Population, total",SP.POP.TOTL,11486631.0,11638712.0,11805689.0,11965966.0,12127120.0,12294732.0,...,16804432.0,16865008.0,16939923.0,17030314.0,17131296.0,17231624.0,17344874.0,17441500.0,17533044.0,17700982.0
177,Norway,NOR,"Population, total",SP.POP.TOTL,3581239.0,3609800.0,3638918.0,3666537.0,3694339.0,3723168.0,...,5079623.0,5137232.0,5188607.0,5234519.0,5276968.0,5311916.0,5347896.0,5379475.0,5408320.0,5457127.0
190,Poland,POL,"Population, total",SP.POP.TOTL,29637450.0,29964000.0,30308500.0,30712000.0,31139450.0,31444950.0,...,38040196.0,38011735.0,37986412.0,37970087.0,37974826.0,37974750.0,37965475.0,37899070.0,37747124.0,36821749.0
194,Portugal,PRT,"Population, total",SP.POP.TOTL,8857716.0,8929316.0,8993985.0,9030355.0,9035365.0,8998595.0,...,10457295.0,10401062.0,10358076.0,10325452.0,10300300.0,10283822.0,10286263.0,10297081.0,10361831.0,10409704.0
201,Romania,ROU,"Population, total",SP.POP.TOTL,18406905.0,18555250.0,18676550.0,18797850.0,18919126.0,19031576.0,...,19983693.0,19908979.0,19815616.0,19702267.0,19588715.0,19473970.0,19371648.0,19265250.0,19122059.0,19047009.0
214,Serbia,SRB,"Population, total",SP.POP.TOTL,6608000.0,6655000.0,6696000.0,6732000.0,6765000.0,6794000.0,...,7164132.0,7130576.0,7095383.0,7058322.0,7020858.0,6982604.0,6945235.0,6899126.0,6834326.0,6664449.0
221,Slovak Republic,SVK,"Population, total",SP.POP.TOTL,4068095.0,4191667.0,4238188.0,4282017.0,4327341.0,4370983.0,...,5413393.0,5418649.0,5423801.0,5430798.0,5439232.0,5446771.0,5454147.0,5458827.0,5447247.0,5431752.0
222,Slovenia,SVN,"Population, total",SP.POP.TOTL,1584720.0,1594131.0,1603649.0,1616971.0,1632114.0,1649160.0,...,2059953.0,2061980.0,2063531.0,2065042.0,2066388.0,2073894.0,2088385.0,2102419.0,2108079.0,2111986.0
223,Sweden,SWE,"Population, total",SP.POP.TOTL,7484656.0,7519998.0,7561588.0,7604328.0,7661354.0,7733853.0,...,9600379.0,9696110.0,9799186.0,9923085.0,10057698.0,10175214.0,10278887.0,10353442.0,10415811.0,10486941.0
244,Turkiye,TUR,"Population, total",SP.POP.TOTL,27510980.0,28255002.0,29033647.0,29827877.0,30612821.0,31374536.0,...,76147624.0,77181884.0,78218479.0,79277962.0,80312698.0,81407204.0,82579440.0,83384680.0,84147318.0,84979913.0

In [17]:
income_df = income_df[income_df['Country Code'].isin(valid_country_codes)]

income_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
5,Albania,ALB,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3757.696946,3844.277141,3277.788243,3467.347570,3729.968219,4340.919854,4361.999293,4322.549675,5262.913596,NaN
14,Austria,AUT,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,41694.071410,42465.766610,35811.685780,37196.167750,38441.732720,41651.807390,40712.575340,39515.557410,43281.733480,NaN
17,Belgium,BEL,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,38766.038040,39529.631060,33799.739830,34528.490590,36341.191070,39046.701410,38340.122000,36801.281740,41743.014280,NaN
21,Bulgaria,BGR,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6422.010445,6643.095885,5819.877624,6238.054937,6970.955514,7752.822898,8165.632881,8311.253957,10114.523520,NaN
37,Switzerland,CHE,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,69446.630990,68999.918110,66347.416160,63668.848940,63071.250220,63208.827090,62588.336180,62971.416170,69631.658240,NaN
53,Cyprus,CYP,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,23695.255860,22731.183590,20165.851560,20629.857420,22676.039060,24887.570310,24414.591800,22488.416020,24687.482420,NaN
54,Czechia,CZE,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,14511.859550,14284.856690,12903.368090,13479.639180,15315.252110,17451.200670,17471.655290,16844.235110,19843.782910,NaN
55,Germany,DEU,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,38946.313070,40356.483120,34656.441910,35663.678890,37760.339680,40854.555970,39718.002330,39043.097150,42982.481890,NaN
58,Denmark,DNK,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,51939.826360,53755.909090,45798.029800,46794.911370,49220.803910,52836.996120,50967.611500,52242.031370,58796.359930,NaN
70,Spain,ESP,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,24246.780770,24700.290100,21716.487970,22489.733440,23874.662000,25791.535570,25125.871720,22321.683940,25118.453140,NaN
71,Estonia,EST,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,15315.388440,16276.911330,14040.886020,14872.602420,16600.900750,18854.373310,19062.769490,19133.100650,22462.364750,NaN
75,Finland,FIN,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,40439.567250,41149.747880,35093.914640,35796.982580,37839.342440,40864.148370,39659.405240,40405.343870,44416.200200,NaN
77,France,FRA,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,35875.673830,36234.531200,30908.686330,31203.694850,32666.612560,34960.740760,33895.528770,31922.266090,36489.804090,NaN
81,United Kingdom,GBR,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,36085.945950,39539.116500,37441.028420,34104.356810,34065.891030,36072.663210,NaN,NaN,NaN,NaN
89,Greece,GRC,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,17844.248420,17998.023520,15044.374440,14903.304930,15546.666000,16496.935840,16155.113670,14754.743490,17262.586540,NaN
99,Croatia,HRV,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,11207.391370,11208.431820,9996.732777,10236.258320,11349.110950,12669.631860,12740.008500,11828.053960,14553.412930,NaN
101,Hungary,HUN,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,10828.651720,11185.671090,9983.018368,10567.309640,11639.406170,13155.833800,13651.960480,12911.789030,14799.383800,NaN
111,Ireland,IRL,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,35850.357050,38740.091700,34222.829920,35982.577770,38093.974820,41648.300450,42297.147920,39973.740210,49607.175420,NaN
114,Iceland,ISL,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,39104.098090,43168.214110,42267.312470,49914.179370,58236.912050,58426.799150,57484.496090,48009.386200,54204.424350,NaN
116,Italy,ITA,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,28943.544610,29060.830990,24535.584580,25551.440400,26867.811920,28897.696280,28011.165480,26185.782590,29681.557130,NaN
137,Liechtenstein,LIE,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,Lithuania,LTU,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,13291.952250,14168.397870,11842.932740,12474.145430,14132.882990,16199.395140,16457.095730,17108.310660,19957.147930,NaN
144,Luxembourg,LUX,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,72403.408510,75837.978480,55729.104160,58461.799890,66052.638050,69498.273760,62146.077050,66535.389550,77781.175700,NaN
145,Latvia,LVA,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,11293.152100,11936.758860,10454.851660,11023.219060,12167.366130,13751.569190,13837.831740,14147.461270,16238.889760,NaN
157,North Macedonia,MKD,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4130.954621,4361.608148,3840.631976,4055.363776,4360.233546,4842.815446,4780.283819,4769.857803,5334.163986,NaN
159,Malta,MLT,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,Montenegro,MNE,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6424.363178,6523.412900,5880.513496,6166.840414,7028.304223,7834.487269,7878.679567,6828.855865,8483.015981,NaN
176,Netherlands,NLD,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,42399.313950,43058.080460,36999.532440,37170.143760,40003.301820,43940.042400,42706.659130,41293.757370,46419.707120,NaN
177,Norway,NOR,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,81275.574700,78188.048940,61241.287330,58475.323880,61772.577710,66488.263380,60649.023130,53949.802500,69953.019230,NaN
190,Poland,POL,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,11445.939400,11957.209040,10613.080620,10405.661260,11609.618130,13050.242230,13241.256600,13333.543280,15098.239660,NaN
194,Portugal,PRT,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,17588.490930,17781.067520,15410.878010,16058.319570,17263.457030,18831.445310,18587.777080,17471.065560,19318.467560,NaN
201,Romania,ROU,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7498.974513,8035.845581,7210.654432,7538.865946,8658.807084,10026.952130,10527.767510,10801.983540,12194.363630,NaN
214,Serbia,SRB,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5535.674049,5426.731356,4584.557262,4679.413515,5026.221826,5868.807072,5940.804379,6351.269736,7431.640563,NaN
221,Slovak Republic,SVK,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,14882.058560,15227.836610,13194.827100,13276.437400,14248.591610,15891.483960,15653.308220,15875.115630,17386.339380,NaN
222,Slovenia,SVN,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,18184.308070,18948.936690,15900.327560,16741.112050,18495.236350,20777.206770,20799.559780,20345.776110,23493.474900,NaN
223,Sweden,SWE,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,52089.635280,51104.430770,43373.545430,43610.186700,45639.940560,46269.208670,44558.122930,45322.007070,51830.626610,NaN
244,Turkiye,TUR,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,10665.187200,10269.293410,9294.272812,9193.574206,8921.211220,8063.601198,7621.523127,7197.801955,NaN,NaN

In [18]:
# Convert column names to strings in population_df
population_df.columns = population_df.columns.astype(str)

# Convert column names to strings in income_df
income_df.columns = income_df.columns.astype(str)

# Convert column names to strings in rail_df
rail_df.columns = rail_df.columns.astype(str)

# Convert column names to strings in air_df
air_df.columns = air_df.columns.astype(str)

In [19]:
# Extract column names from rail_df
valid_columns = rail_df.columns

# Filter columns in population_df and income_df based on valid column names
population_df = population_df[valid_columns.intersection(population_df.columns)]
population_df

,Country Name,Country Code,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
5,Albania,ALB,2905195.0,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0,2866376.0,2854191.0,2837849.0,2811666.0,2777689.0
14,Austria,AUT,8391643.0,8429991.0,8479823.0,8546356.0,8642699.0,8736668.0,8797566.0,8840521.0,8879920.0,8916864.0,8955797.0,9041851.0
17,Belgium,BEL,11038264.0,11106932.0,11159407.0,11209057.0,11274196.0,11331422.0,11375158.0,11427054.0,11488980.0,11538604.0,11586195.0,11685814.0
21,Bulgaria,BGR,7348328.0,7305888.0,7265115.0,7223938.0,7177991.0,7127822.0,7075947.0,7025037.0,6975761.0,6934015.0,6877743.0,6465097.0
37,Switzerland,CHE,7912398.0,7996861.0,8089346.0,8188649.0,8282396.0,8373338.0,8451840.0,8514329.0,8575280.0,8638167.0,8704546.0,8775760.0
53,Cyprus,CYP,1145086.0,1156556.0,1166968.0,1176995.0,1187280.0,1197881.0,1208523.0,1218831.0,1228836.0,1237537.0,1244188.0,1251488.0
54,Czechia,CZE,10496088.0,10510785.0,10514272.0,10525347.0,10546059.0,10566332.0,10594438.0,10629928.0,10671870.0,10697858.0,10505772.0,10672118.0
55,Germany,DEU,80274983.0,80425823.0,80645605.0,80982500.0,81686611.0,82348669.0,82657002.0,82905782.0,83092962.0,83160871.0,83196078.0,83797985.0
58,Denmark,DNK,5570572.0,5591572.0,5614932.0,5643475.0,5683483.0,5728010.0,5764980.0,5793636.0,5814422.0,5831404.0,5856733.0,5903037.0
70,Spain,ESP,46742697.0,46773055.0,46620045.0,46480882.0,46444832.0,46484062.0,46593236.0,46797754.0,47134837.0,47365655.0,47415794.0,47778340.0
71,Estonia,EST,1327439.0,1322696.0,1317997.0,1314545.0,1315407.0,1315790.0,1317384.0,1321977.0,1326898.0,1329522.0,1330932.0,1348840.0
75,Finland,FIN,5388272.0,5413971.0,5438972.0,5461512.0,5479531.0,5495303.0,5508214.0,5515525.0,5521606.0,5529543.0,5541017.0,5556106.0
77,France,FRA,65345233.0,65662240.0,66002289.0,66312067.0,66548272.0,66724104.0,66918020.0,67158348.0,67388001.0,67571107.0,67764304.0,67971311.0
81,United Kingdom,GBR,63258810.0,63700215.0,64128273.0,64602298.0,65116219.0,65611593.0,66058859.0,66460344.0,66836327.0,67081234.0,67026292.0,66971395.0
89,Greece,GRC,11104899.0,11045011.0,10965211.0,10892413.0,10820883.0,10775971.0,10754679.0,10732882.0,10721582.0,10698599.0,10569207.0,10426919.0
99,Croatia,HRV,4280622.0,4267558.0,4255689.0,4238389.0,4203604.0,4174349.0,4124531.0,4087843.0,4065253.0,4047680.0,3879000.0,3855600.0
101,Hungary,HUN,9971727.0,9920362.0,9893082.0,9866468.0,9843028.0,9814023.0,9787966.0,9775564.0,9771141.0,9750149.0,9709891.0,9643048.0
111,Ireland,IRL,4580084.0,4599533.0,4623816.0,4657740.0,4701957.0,4755335.0,4807388.0,4867316.0,4934340.0,4985382.0,5033164.0,5127170.0
114,Iceland,ISL,319014.0,320716.0,323764.0,327386.0,330815.0,335439.0,343400.0,352721.0,360563.0,366463.0,372520.0,382003.0
116,Italy,ITA,59379449.0,59539717.0,60233948.0,60789140.0,60730582.0,60627498.0,60536709.0,60421760.0,59729081.0,59438851.0,59133173.0,58940425.0
137,Liechtenstein,LIE,36189.0,36505.0,36806.0,37096.0,37355.0,37609.0,37889.0,38181.0,38482.0,38756.0,39039.0,39327.0
143,Lithuania,LTU,3028115.0,2987773.0,2957689.0,2932367.0,2904910.0,2868231.0,2828403.0,2801543.0,2794137.0,2794885.0,2800839.0,2831639.0
144,Luxembourg,LUX,518347.0,530946.0,543360.0,556319.0,569604.0,582014.0,596336.0,607950.0,620001.0,630419.0,640064.0,653103.0
145,Latvia,LVA,2059709.0,2034319.0,2012647.0,1993782.0,1977527.0,1959537.0,1942248.0,1927174.0,1913822.0,1900449.0,1884490.0,1879383.0
157,North Macedonia,MKD,2058539.0,2061044.0,2064032.0,2067471.0,2070226.0,2072490.0,2074502.0,2076217.0,2076694.0,2072531.0,2065092.0,2057679.0
159,Malta,MLT,416268.0,420028.0,425967.0,434558.0,445053.0,455356.0,467999.0,484630.0,504062.0,515332.0,518536.0,531113.0
162,Montenegro,MNE,620079.0,620601.0,621207.0,621810.0,622159.0,622303.0,622373.0,622227.0,622028.0,621306.0,619211.0,617213.0
176,Netherlands,NLD,16693074.0,16754962.0,16804432.0,16865008.0,16939923.0,17030314.0,17131296.0,17231624.0,17344874.0,17441500.0,17533044.0,17700982.0
177,Norway,NOR,4953088.0,5018573.0,5079623.0,5137232.0,5188607.0,5234519.0,5276968.0,5311916.0,5347896.0,5379475.0,5408320.0,5457127.0
190,Poland,POL,38063255.0,38063164.0,38040196.0,38011735.0,37986412.0,37970087.0,37974826.0,37974750.0,37965475.0,37899070.0,37747124.0,36821749.0
194,Portugal,PRT,10557560.0,10514844.0,10457295.0,10401062.0,10358076.0,10325452.0,10300300.0,10283822.0,10286263.0,10297081.0,10361831.0,10409704.0
201,Romania,ROU,20147528.0,20058035.0,19983693.0,19908979.0,19815616.0,19702267.0,19588715.0,19473970.0,19371648.0,19265250.0,19122059.0,19047009.0
214,Serbia,SRB,7234099.0,7199077.0,7164132.0,7130576.0,7095383.0,7058322.0,7020858.0,6982604.0,6945235.0,6899126.0,6834326.0,6664449.0
221,Slovak Republic,SVK,5398384.0,5407579.0,5413393.0,5418649.0,5423801.0,5430798.0,5439232.0,5446771.0,5454147.0,5458827.0,5447247.0,5431752.0
222,Slovenia,SVN,2052843.0,2057159.0,2059953.0,2061980.0,2063531.0,2065042.0,2066388.0,2073894.0,2088385.0,2102419.0,2108079.0,2111986.0
223,Sweden,SWE,9449213.0,9519374.0,9600379.0,9696110.0,9799186.0,9923085.0,10057698.0,10175214.0,10278887.0,10353442.0,10415811.0,10486941.0
244,Turkiye,TUR,74223629.0,75175827.0,76147624.0,77181884.0,78218479.0,79277962.0,80312698.0,81407204.0,82579440.0,83384680.0,84147318.0,84979913.0

In [20]:
income_df = income_df[valid_columns.intersection(income_df.columns)]
income_df

,Country Name,Country Code,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
5,Albania,ALB,3753.965485,3522.372857,3757.696946,3844.277141,3277.788243,3467.347570,3729.968219,4340.919854,4361.999293,4322.549675,5262.913596,NaN
14,Austria,AUT,42625.237350,39980.630840,41694.071410,42465.766610,35811.685780,37196.167750,38441.732720,41651.807390,40712.575340,39515.557410,43281.733480,NaN
17,Belgium,BEL,38266.983740,36945.841000,38766.038040,39529.631060,33799.739830,34528.490590,36341.191070,39046.701410,38340.122000,36801.281740,41743.014280,NaN
21,Bulgaria,BGR,6408.162620,6243.723979,6422.010445,6643.095885,5819.877624,6238.054937,6970.955514,7752.822898,8165.632881,8311.253957,10114.523520,NaN
37,Switzerland,CHE,70650.760300,68518.989360,69446.630990,68999.918110,66347.416160,63668.848940,63071.250220,63208.827090,62588.336180,62971.416170,69631.658240,NaN
53,Cyprus,CYP,29378.478520,25145.888670,23695.255860,22731.183590,20165.851560,20629.857420,22676.039060,24887.570310,24414.591800,22488.416020,24687.482420,NaN
54,Czechia,CZE,15447.399680,14334.344300,14511.859550,14284.856690,12903.368090,13479.639180,15315.252110,17451.200670,17471.655290,16844.235110,19843.782910,NaN
55,Germany,DEU,39563.817330,36959.968930,38946.313070,40356.483120,34656.441910,35663.678890,37760.339680,40854.555970,39718.002330,39043.097150,42982.481890,NaN
58,Denmark,DNK,51361.501820,48806.803020,51939.826360,53755.909090,45798.029800,46794.911370,49220.803910,52836.996120,50967.611500,52242.031370,58796.359930,NaN
70,Spain,ESP,26212.695890,23566.205090,24246.780770,24700.290100,21716.487970,22489.733440,23874.662000,25791.535570,25125.871720,22321.683940,25118.453140,NaN
71,Estonia,EST,13704.931510,13778.337230,15315.388440,16276.911330,14040.886020,14872.602420,16600.900750,18854.373310,19062.769490,19133.100650,22462.364750,NaN
75,Finland,FIN,41789.955880,38711.309790,40439.567250,41149.747880,35093.914640,35796.982580,37839.342440,40864.148370,39659.405240,40405.343870,44416.200200,NaN
77,France,FRA,37186.936050,34392.293850,35875.673830,36234.531200,30908.686330,31203.694850,32666.612560,34960.740760,33895.528770,31922.266090,36489.804090,NaN
81,United Kingdom,GBR,35752.958200,35519.330190,36085.945950,39539.116500,37441.028420,34104.356810,34065.891030,36072.663210,NaN,NaN,NaN,NaN
89,Greece,GRC,20268.839910,18108.189410,17844.248420,17998.023520,15044.374440,14903.304930,15546.666000,16496.935840,16155.113670,14754.743490,17262.586540,NaN
99,Croatia,HRV,11677.725470,10607.642930,11207.391370,11208.431820,9996.732777,10236.258320,11349.110950,12669.631860,12740.008500,11828.053960,14553.412930,NaN
101,Hungary,HUN,10941.720040,10013.359400,10828.651720,11185.671090,9983.018368,10567.309640,11639.406170,13155.833800,13651.960480,12911.789030,14799.383800,NaN
111,Ireland,IRL,35191.623130,32552.740140,35850.357050,38740.091700,34222.829920,35982.577770,38093.974820,41648.300450,42297.147920,39973.740210,49607.175420,NaN
114,Iceland,ISL,32094.720220,32294.153180,39104.098090,43168.214110,42267.312470,49914.179370,58236.912050,58426.799150,57484.496090,48009.386200,54204.424350,NaN
116,Italy,ITA,31676.031770,28562.819180,28943.544610,29060.830990,24535.584580,25551.440400,26867.811920,28897.696280,28011.165480,26185.782590,29681.557130,NaN
137,Liechtenstein,LIE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,Lithuania,LTU,12036.580420,12013.395370,13291.952250,14168.397870,11842.932740,12474.145430,14132.882990,16199.395140,16457.095730,17108.310660,19957.147930,NaN
144,Luxembourg,LUX,68844.401650,73525.228600,72403.408510,75837.978480,55729.104160,58461.799890,66052.638050,69498.273760,62146.077050,66535.389550,77781.175700,NaN
145,Latvia,LVA,9962.779893,10297.666030,11293.152100,11936.758860,10454.851660,11023.219060,12167.366130,13751.569190,13837.831740,14147.461270,16238.889760,NaN
157,North Macedonia,MKD,4003.648041,3678.204435,4130.954621,4361.608148,3840.631976,4055.363776,4360.233546,4842.815446,4780.283819,4769.857803,5334.163986,NaN
159,Malta,MLT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,Montenegro,MNE,6553.322168,5887.144304,6424.363178,6523.412900,5880.513496,6166.840414,7028.304223,7834.487269,7878.679567,6828.855865,8483.015981,NaN
176,Netherlands,NLD,44453.574190,40527.215080,42399.313950,43058.080460,36999.532440,37170.143760,40003.301820,43940.042400,42706.659130,41293.757370,46419.707120,NaN
177,Norway,NOR,77792.246290,79207.141700,81275.574700,78188.048940,61241.287330,58475.323880,61772.577710,66488.263380,60649.023130,53949.802500,69953.019230,NaN
190,Poland,POL,11566.237160,11004.725190,11445.939400,11957.209040,10613.080620,10405.661260,11609.618130,13050.242230,13241.256600,13333.543280,15098.239660,NaN
194,Portugal,PRT,18736.508050,16374.401440,17588.490930,17781.067520,15410.878010,16058.319570,17263.457030,18831.445310,18587.777080,17471.065560,19318.467560,NaN
201,Romania,ROU,7534.116193,7016.996323,7498.974513,8035.845581,7210.654432,7538.865946,8658.807084,10026.952130,10527.767510,10801.983540,12194.363630,NaN
214,Serbia,SRB,5472.781189,4879.443718,5535.674049,5426.731356,4584.557262,4679.413515,5026.221826,5868.807072,5940.804379,6351.269736,7431.640563,NaN
221,Slovak Republic,SVK,14577.732430,14119.209770,14882.058560,15227.836610,13194.827100,13276.437400,14248.591610,15891.483960,15653.308220,15875.115630,17386.339380,NaN
222,Slovenia,SVN,19709.885230,17479.583020,18184.308070,18948.936690,15900.327560,16741.112050,18495.236350,20777.206770,20799.559780,20345.776110,23493.474900,NaN
223,Sweden,SWE,51652.818110,49429.392370,52089.635280,51104.430770,43373.545430,43610.186700,45639.940560,46269.208670,44558.122930,45322.007070,51830.626610,NaN
244,Turkiye,TUR,9534.737344,9895.728768,10665.187200,10269.293410,9294.272812,9193.574206,8921.211220,8063.601198,7621.523127,7197.801955,NaN,NaN

In [21]:
def process_dataframe(input_df):
    # Step 1: Make a copy of the DataFrame without the first two columns
    df_copy = input_df.iloc[:, 2:].copy()

    # Display all rows in the copy DataFrame with no data
    empty_rows = df_copy[df_copy.isnull().all(axis=1)]
    print("Rows with no data in the copy DataFrame:")
    print(empty_rows)

    # Step 3: Remove rows with no data from the original DataFrame
    input_df.drop(empty_rows.index, inplace=True)

# List of DataFrames
dataframes = [income_df, population_df, rail_df, air_df]

# Process each DataFrame using a loop
for df in dataframes:
    print(f"Processing DataFrame:")
    process_dataframe(df)
    print("\n" + "="*40 + "\n")  # Separating output for better readability

Processing DataFrame:
Rows with no data in the copy DataFrame:
     2011  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021  2022
137   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
159   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

========================================

Processing DataFrame:
Rows with no data in the copy DataFrame:
Empty DataFrame
Columns: [2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
Index: []

========================================

Processing DataFrame:
Rows with no data in the copy DataFrame:
    2011  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021  2022
34   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
27   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
28   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
17   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
32   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
18   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
35   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
12   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

========================================

Processing DataFrame:
Rows with no data in the copy DataFrame:
    2011  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021  2022
35   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
28   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
37   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

========================================

C:\Users\fadiez\AppData\Local\Temp\ipykernel_16488\3709896903.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  input_df.drop(empty_rows.index, inplace=True)
C:\Users\fadiez\AppData\Local\Temp\ipykernel_16488\3709896903.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  input_df.drop(empty_rows.index, inplace=True)

In [22]:
income_df

,Country Name,Country Code,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
5,Albania,ALB,3753.965485,3522.372857,3757.696946,3844.277141,3277.788243,3467.347570,3729.968219,4340.919854,4361.999293,4322.549675,5262.913596,NaN
14,Austria,AUT,42625.237350,39980.630840,41694.071410,42465.766610,35811.685780,37196.167750,38441.732720,41651.807390,40712.575340,39515.557410,43281.733480,NaN
17,Belgium,BEL,38266.983740,36945.841000,38766.038040,39529.631060,33799.739830,34528.490590,36341.191070,39046.701410,38340.122000,36801.281740,41743.014280,NaN
21,Bulgaria,BGR,6408.162620,6243.723979,6422.010445,6643.095885,5819.877624,6238.054937,6970.955514,7752.822898,8165.632881,8311.253957,10114.523520,NaN
37,Switzerland,CHE,70650.760300,68518.989360,69446.630990,68999.918110,66347.416160,63668.848940,63071.250220,63208.827090,62588.336180,62971.416170,69631.658240,NaN
53,Cyprus,CYP,29378.478520,25145.888670,23695.255860,22731.183590,20165.851560,20629.857420,22676.039060,24887.570310,24414.591800,22488.416020,24687.482420,NaN
54,Czechia,CZE,15447.399680,14334.344300,14511.859550,14284.856690,12903.368090,13479.639180,15315.252110,17451.200670,17471.655290,16844.235110,19843.782910,NaN
55,Germany,DEU,39563.817330,36959.968930,38946.313070,40356.483120,34656.441910,35663.678890,37760.339680,40854.555970,39718.002330,39043.097150,42982.481890,NaN
58,Denmark,DNK,51361.501820,48806.803020,51939.826360,53755.909090,45798.029800,46794.911370,49220.803910,52836.996120,50967.611500,52242.031370,58796.359930,NaN
70,Spain,ESP,26212.695890,23566.205090,24246.780770,24700.290100,21716.487970,22489.733440,23874.662000,25791.535570,25125.871720,22321.683940,25118.453140,NaN
71,Estonia,EST,13704.931510,13778.337230,15315.388440,16276.911330,14040.886020,14872.602420,16600.900750,18854.373310,19062.769490,19133.100650,22462.364750,NaN
75,Finland,FIN,41789.955880,38711.309790,40439.567250,41149.747880,35093.914640,35796.982580,37839.342440,40864.148370,39659.405240,40405.343870,44416.200200,NaN
77,France,FRA,37186.936050,34392.293850,35875.673830,36234.531200,30908.686330,31203.694850,32666.612560,34960.740760,33895.528770,31922.266090,36489.804090,NaN
81,United Kingdom,GBR,35752.958200,35519.330190,36085.945950,39539.116500,37441.028420,34104.356810,34065.891030,36072.663210,NaN,NaN,NaN,NaN
89,Greece,GRC,20268.839910,18108.189410,17844.248420,17998.023520,15044.374440,14903.304930,15546.666000,16496.935840,16155.113670,14754.743490,17262.586540,NaN
99,Croatia,HRV,11677.725470,10607.642930,11207.391370,11208.431820,9996.732777,10236.258320,11349.110950,12669.631860,12740.008500,11828.053960,14553.412930,NaN
101,Hungary,HUN,10941.720040,10013.359400,10828.651720,11185.671090,9983.018368,10567.309640,11639.406170,13155.833800,13651.960480,12911.789030,14799.383800,NaN
111,Ireland,IRL,35191.623130,32552.740140,35850.357050,38740.091700,34222.829920,35982.577770,38093.974820,41648.300450,42297.147920,39973.740210,49607.175420,NaN
114,Iceland,ISL,32094.720220,32294.153180,39104.098090,43168.214110,42267.312470,49914.179370,58236.912050,58426.799150,57484.496090,48009.386200,54204.424350,NaN
116,Italy,ITA,31676.031770,28562.819180,28943.544610,29060.830990,24535.584580,25551.440400,26867.811920,28897.696280,28011.165480,26185.782590,29681.557130,NaN
143,Lithuania,LTU,12036.580420,12013.395370,13291.952250,14168.397870,11842.932740,12474.145430,14132.882990,16199.395140,16457.095730,17108.310660,19957.147930,NaN
144,Luxembourg,LUX,68844.401650,73525.228600,72403.408510,75837.978480,55729.104160,58461.799890,66052.638050,69498.273760,62146.077050,66535.389550,77781.175700,NaN
145,Latvia,LVA,9962.779893,10297.666030,11293.152100,11936.758860,10454.851660,11023.219060,12167.366130,13751.569190,13837.831740,14147.461270,16238.889760,NaN
157,North Macedonia,MKD,4003.648041,3678.204435,4130.954621,4361.608148,3840.631976,4055.363776,4360.233546,4842.815446,4780.283819,4769.857803,5334.163986,NaN
162,Montenegro,MNE,6553.322168,5887.144304,6424.363178,6523.412900,5880.513496,6166.840414,7028.304223,7834.487269,7878.679567,6828.855865,8483.015981,NaN
176,Netherlands,NLD,44453.574190,40527.215080,42399.313950,43058.080460,36999.532440,37170.143760,40003.301820,43940.042400,42706.659130,41293.757370,46419.707120,NaN
177,Norway,NOR,77792.246290,79207.141700,81275.574700,78188.048940,61241.287330,58475.323880,61772.577710,66488.263380,60649.023130,53949.802500,69953.019230,NaN
190,Poland,POL,11566.237160,11004.725190,11445.939400,11957.209040,10613.080620,10405.661260,11609.618130,13050.242230,13241.256600,13333.543280,15098.239660,NaN
194,Portugal,PRT,18736.508050,16374.401440,17588.490930,17781.067520,15410.878010,16058.319570,17263.457030,18831.445310,18587.777080,17471.065560,19318.467560,NaN
201,Romania,ROU,7534.116193,7016.996323,7498.974513,8035.845581,7210.654432,7538.865946,8658.807084,10026.952130,10527.767510,10801.983540,12194.363630,NaN
214,Serbia,SRB,5472.781189,4879.443718,5535.674049,5426.731356,4584.557262,4679.413515,5026.221826,5868.807072,5940.804379,6351.269736,7431.640563,NaN
221,Slovak Republic,SVK,14577.732430,14119.209770,14882.058560,15227.836610,13194.827100,13276.437400,14248.591610,15891.483960,15653.308220,15875.115630,17386.339380,NaN
222,Slovenia,SVN,19709.885230,17479.583020,18184.308070,18948.936690,15900.327560,16741.112050,18495.236350,20777.206770,20799.559780,20345.776110,23493.474900,NaN
223,Sweden,SWE,51652.818110,49429.392370,52089.635280,51104.430770,43373.545430,43610.186700,45639.940560,46269.208670,44558.122930,45322.007070,51830.626610,NaN
244,Turkiye,TUR,9534.737344,9895.728768,10665.187200,10269.293410,9294.272812,9193.574206,8921.211220,8063.601198,7621.523127,7197.801955,NaN,NaN

In [23]:
# List of DataFrames
dataframes = [income_df, population_df, rail_df, air_df]

# Extract unique "Country Code" values from each DataFrame
common_codes = set(dataframes[0]['Country Code'].unique())
for df in dataframes[1:]:
    common_codes &= set(df['Country Code'].unique())

# Filter each DataFrame to keep only rows with common "Country Code" values
for i, df in enumerate(dataframes):
    dataframes[i] = df[df['Country Code'].isin(common_codes)]

# Display the modified DataFrames with common "Country Code" values
for i, df in enumerate(dataframes):
    print(f"{df} DataFrame with common Country Codes:")
    print(df)
    print("\n" + "="*40 + "\n")  # Separating output for better readability

        Country Name Country Code          2011          2012          2013  \
14           Austria          AUT  42625.237350  39980.630840  41694.071410
17           Belgium          BEL  38266.983740  36945.841000  38766.038040
21          Bulgaria          BGR   6408.162620   6243.723979   6422.010445
37       Switzerland          CHE  70650.760300  68518.989360  69446.630990
54           Czechia          CZE  15447.399680  14334.344300  14511.859550
55           Germany          DEU  39563.817330  36959.968930  38946.313070
58           Denmark          DNK  51361.501820  48806.803020  51939.826360
70             Spain          ESP  26212.695890  23566.205090  24246.780770
71           Estonia          EST  13704.931510  13778.337230  15315.388440
75           Finland          FIN  41789.955880  38711.309790  40439.567250
77            France          FRA  37186.936050  34392.293850  35875.673830
81    United Kingdom          GBR  35752.958200  35519.330190  36085.945950
89            Greece          GRC  20268.839910  18108.189410  17844.248420
99           Croatia          HRV  11677.725470  10607.642930  11207.391370
101          Hungary          HUN  10941.720040  10013.359400  10828.651720
111          Ireland          IRL  35191.623130  32552.740140  35850.357050
116            Italy          ITA  31676.031770  28562.819180  28943.544610
143        Lithuania          LTU  12036.580420  12013.395370  13291.952250
144       Luxembourg          LUX  68844.401650  73525.228600  72403.408510
145           Latvia          LVA   9962.779893  10297.666030  11293.152100
157  North Macedonia          MKD   4003.648041   3678.204435   4130.954621
177           Norway          NOR  77792.246290  79207.141700  81275.574700
190           Poland          POL  11566.237160  11004.725190  11445.939400
194         Portugal          PRT  18736.508050  16374.401440  17588.490930
201          Romania          ROU   7534.116193   7016.996323   7498.974513
221  Slovak Republic          SVK  14577.732430  14119.209770  14882.058560
222         Slovenia          SVN  19709.885230  17479.583020  18184.308070
223           Sweden          SWE  51652.818110  49429.392370  52089.635280

             2014          2015          2016          2017          2018  \
14   42465.766610  35811.685780  37196.167750  38441.732720  41651.807390
17   39529.631060  33799.739830  34528.490590  36341.191070  39046.701410
21    6643.095885   5819.877624   6238.054937   6970.955514   7752.822898
37   68999.918110  66347.416160  63668.848940  63071.250220  63208.827090
54   14284.856690  12903.368090  13479.639180  15315.252110  17451.200670
55   40356.483120  34656.441910  35663.678890  37760.339680  40854.555970
58   53755.909090  45798.029800  46794.911370  49220.803910  52836.996120
70   24700.290100  21716.487970  22489.733440  23874.662000  25791.535570
71   16276.911330  14040.886020  14872.602420  16600.900750  18854.373310
75   41149.747880  35093.914640  35796.982580  37839.342440  40864.148370
77   36234.531200  30908.686330  31203.694850  32666.612560  34960.740760
81   39539.116500  37441.028420  34104.356810  34065.891030  36072.663210
89   17998.023520  15044.374440  14903.304930  15546.666000  16496.935840
99   11208.431820   9996.732777  10236.258320  11349.110950  12669.631860
101  11185.671090   9983.018368  10567.309640  11639.406170  13155.833800
111  38740.091700  34222.829920  35982.577770  38093.974820  41648.300450
116  29060.830990  24535.584580  25551.440400  26867.811920  28897.696280
143  14168.397870  11842.932740  12474.145430  14132.882990  16199.395140
144  75837.978480  55729.104160  58461.799890  66052.638050  69498.273760
145  11936.758860  10454.851660  11023.219060  12167.366130  13751.569190
157   4361.608148   3840.631976   4055.363776   4360.233546   4842.815446
177  78188.048940  61241.287330  58475.323880  61772.577710  66488.263380
190  11957.209040  10613.080620  10405.661260  11609.618130  13050.242230
194  17781.067520  15410.878010  16058.319570  17263.457030  18831.445310
201   8035.845581   7210.654432   7538.865946   8658.807084  10026.952130
221  15227.836610  13194.827100  13276.437400  14248.591610  15891.483960
222  18948.936690  15900.327560  16741.112050  18495.236350  20777.206770
223  51104.430770  43373.545430  43610.186700  45639.940560  46269.208670

             2019          2020          2021  2022
14   40712.575340  39515.557410  43281.733480   NaN
17   38340.122000  36801.281740  41743.014280   NaN
21    8165.632881   8311.253957  10114.523520   NaN
37   62588.336180  62971.416170  69631.658240   NaN
54   17471.655290  16844.235110  19843.782910   NaN
55   39718.002330  39043.097150  42982.481890   NaN
58   50967.611500  52242.031370  58796.359930   NaN
70   25125.871720  22321.683940  25118.453140   NaN
71   19062.769490  19133.100650  22462.364750   NaN
75   39659.405240  40405.343870  44416.200200   NaN
77   33895.528770  31922.266090  36489.804090   NaN
81            NaN           NaN           NaN   NaN
89   16155.113670  14754.743490  17262.586540   NaN
99   12740.008500  11828.053960  14553.412930   NaN
101  13651.960480  12911.789030  14799.383800   NaN
111  42297.147920  39973.740210  49607.175420   NaN
116  28011.165480  26185.782590  29681.557130   NaN
143  16457.095730  17108.310660  19957.147930   NaN
144  62146.077050  66535.389550  77781.175700   NaN
145  13837.831740  14147.461270  16238.889760   NaN
157   4780.283819   4769.857803   5334.163986   NaN
177  60649.023130  53949.802500  69953.019230   NaN
190  13241.256600  13333.543280  15098.239660   NaN
194  18587.777080  17471.065560  19318.467560   NaN
201  10527.767510  10801.983540  12194.363630   NaN
221  15653.308220  15875.115630  17386.339380   NaN
222  20799.559780  20345.776110  23493.474900   NaN
223  44558.122930  45322.007070  51830.626610   NaN   DataFrame with common Country Codes:
        Country Name Country Code          2011          2012          2013  \
14           Austria          AUT  42625.237350  39980.630840  41694.071410
17           Belgium          BEL  38266.983740  36945.841000  38766.038040
21          Bulgaria          BGR   6408.162620   6243.723979   6422.010445
37       Switzerland          CHE  70650.760300  68518.989360  69446.630990
54           Czechia          CZE  15447.399680  14334.344300  14511.859550
55           Germany          DEU  39563.817330  36959.968930  38946.313070
58           Denmark          DNK  51361.501820  48806.803020  51939.826360
70             Spain          ESP  26212.695890  23566.205090  24246.780770
71           Estonia          EST  13704.931510  13778.337230  15315.388440
75           Finland          FIN  41789.955880  38711.309790  40439.567250
77            France          FRA  37186.936050  34392.293850  35875.673830
81    United Kingdom          GBR  35752.958200  35519.330190  36085.945950
89            Greece          GRC  20268.839910  18108.189410  17844.248420
99           Croatia          HRV  11677.725470  10607.642930  11207.391370
101          Hungary          HUN  10941.720040  10013.359400  10828.651720
111          Ireland          IRL  35191.623130  32552.740140  35850.357050
116            Italy          ITA  31676.031770  28562.819180  28943.544610
143        Lithuania          LTU  12036.580420  12013.395370  13291.952250
144       Luxembourg          LUX  68844.401650  73525.228600  72403.408510
145           Latvia          LVA   9962.779893  10297.666030  11293.152100
157  North Macedonia          MKD   4003.648041   3678.204435   4130.954621
177           Norway          NOR  77792.246290  79207.141700  81275.574700
190           Poland          POL  11566.237160  11004.725190  11445.939400
194         Portugal          PRT  18736.508050  16374.401440  17588.490930
201          Romania          ROU   7534.116193   7016.996323   7498.974513
221  Slovak Republic          SVK  14577.732430  14119.209770  14882.058560
222         Slovenia          SVN  19709.885230  17479.583020  18184.308070
223           Sweden          SWE  51652.818110  49429.392370  52089.635280

             2014          2015          2016          2017          2018  \
14   42465.766610  35811.685780  37196.167750  38441.732720  41651.807390
17   39529.631060  33799.739830  34528.490590  36341.191070  39046.701410
21    6643.095885   5819.877624   6238.054937   6970.955514   7752.822898
37   68999.918110  66347.416160  63668.848940  63071.250220  63208.827090
54   14284.856690  12903.368090  13479.639180  15315.252110  17451.200670
55   40356.483120  34656.441910  35663.678890  37760.339680  40854.555970
58   53755.909090  45798.029800  46794.911370  49220.803910  52836.996120
70   24700.290100  21716.487970  22489.733440  23874.662000  25791.535570
71   16276.911330  14040.886020  14872.602420  16600.900750  18854.373310
75   41149.747880  35093.914640  35796.982580  37839.342440  40864.148370
77   36234.531200  30908.686330  31203.694850  32666.612560  34960.740760
81   39539.116500  37441.028420  34104.356810  34065.891030  36072.663210
89   17998.023520  15044.374440  14903.304930  15546.666000  16496.935840
99   11208.431820   9996.732777  10236.258320  11349.110950  12669.631860
101  11185.671090   9983.018368  10567.309640  11639.406170  13155.833800
111  38740.091700  34222.829920  35982.577770  38093.974820  41648.300450
116  29060.830990  24535.584580  25551.440400  26867.811920  28897.696280
143  14168.397870  11842.932740  12474.145430  14132.882990  16199.395140
144  75837.978480  55729.104160  58461.799890  66052.638050  69498.273760
145  11936.758860  10454.851660  11023.219060  12167.366130  13751.569190
157   4361.608148   3840.631976   4055.363776   4360.233546   4842.815446
177  78188.048940  61241.287330  58475.323880  61772.577710  66488.263380
190  11957.209040  10613.080620  10405.661260  11609.618130  13050.242230
194  17781.067520  15410.878010  16058.319570  17263.457030  18831.445310
201   8035.845581   7210.654432   7538.865946   8658.807084  10026.952130
221  15227.836610  13194.827100  13276.437400  14248.591610  15891.483960
222  18948.936690  15900.327560  16741.112050  18495.236350  20777.206770
223  51104.430770  43373.545430  43610.186700  45639.940560  46269.208670

             2019          2020          2021  2022
14   40712.575340  39515.557410  43281.733480   NaN
17   38340.122000  36801.281740  41743.014280   NaN
21    8165.632881   8311.253957  10114.523520   NaN
37   62588.336180  62971.416170  69631.658240   NaN
54   17471.655290  16844.235110  19843.782910   NaN
55   39718.002330  39043.097150  42982.481890   NaN
58   50967.611500  52242.031370  58796.359930   NaN
70   25125.871720  22321.683940  25118.453140   NaN
71   19062.769490  19133.100650  22462.364750   NaN
75   39659.405240  40405.343870  44416.200200   NaN
77   33895.528770  31922.266090  36489.804090   NaN
81            NaN           NaN           NaN   NaN
89   16155.113670  14754.743490  17262.586540   NaN
99   12740.008500  11828.053960  14553.412930   NaN
101  13651.960480  12911.789030  14799.383800   NaN
111  42297.147920  39973.740210  49607.175420   NaN
116  28011.165480  26185.782590  29681.557130   NaN
143  16457.095730  17108.310660  19957.147930   NaN
144  62146.077050  66535.389550  77781.175700   NaN
145  13837.831740  14147.461270  16238.889760   NaN
157   4780.283819   4769.857803   5334.163986   NaN
177  60649.023130  53949.802500  69953.019230   NaN
190  13241.256600  13333.543280  15098.239660   NaN
194  18587.777080  17471.065560  19318.467560   NaN
201  10527.767510  10801.983540  12194.363630   NaN
221  15653.308220  15875.115630  17386.339380   NaN
222  20799.559780  20345.776110  23493.474900   NaN
223  44558.122930  45322.007070  51830.626610   NaN

========================================

        Country Name Country Code        2011        2012        2013  \
14           Austria          AUT   8391643.0   8429991.0   8479823.0
17           Belgium          BEL  11038264.0  11106932.0  11159407.0
21          Bulgaria          BGR   7348328.0   7305888.0   7265115.0
37       Switzerland          CHE   7912398.0   7996861.0   8089346.0
54           Czechia          CZE  10496088.0  10510785.0  10514272.0
55           Germany          DEU  80274983.0  80425823.0  80645605.0
58           Denmark          DNK   5570572.0   5591572.0   5614932.0
70             Spain          ESP  46742697.0  46773055.0  46620045.0
71           Estonia          EST   1327439.0   1322696.0   1317997.0
75           Finland          FIN   5388272.0   5413971.0   5438972.0
77            France          FRA  65345233.0  65662240.0  66002289.0
81    United Kingdom          GBR  63258810.0  63700215.0  64128273.0
89            Greece          GRC  11104899.0  11045011.0  10965211.0
99           Croatia          HRV   4280622.0   4267558.0   4255689.0
101          Hungary          HUN   9971727.0   9920362.0   9893082.0
111          Ireland          IRL   4580084.0   4599533.0   4623816.0
116            Italy          ITA  59379449.0  59539717.0  60233948.0
143        Lithuania          LTU   3028115.0   2987773.0   2957689.0
144       Luxembourg          LUX    518347.0    530946.0    543360.0
145           Latvia          LVA   2059709.0   2034319.0   2012647.0
157  North Macedonia          MKD   2058539.0   2061044.0   2064032.0
177           Norway          NOR   4953088.0   5018573.0   5079623.0
190           Poland          POL  38063255.0  38063164.0  38040196.0
194         Portugal          PRT  10557560.0  10514844.0  10457295.0
201          Romania          ROU  20147528.0  20058035.0  19983693.0
221  Slovak Republic          SVK   5398384.0   5407579.0   5413393.0
222         Slovenia          SVN   2052843.0   2057159.0   2059953.0
223           Sweden          SWE   9449213.0   9519374.0   9600379.0

           2014        2015        2016        2017        2018        2019  \
14    8546356.0   8642699.0   8736668.0   8797566.0   8840521.0   8879920.0
17   11209057.0  11274196.0  11331422.0  11375158.0  11427054.0  11488980.0
21    7223938.0   7177991.0   7127822.0   7075947.0   7025037.0   6975761.0
37    8188649.0   8282396.0   8373338.0   8451840.0   8514329.0   8575280.0
54   10525347.0  10546059.0  10566332.0  10594438.0  10629928.0  10671870.0
55   80982500.0  81686611.0  82348669.0  82657002.0  82905782.0  83092962.0
58    5643475.0   5683483.0   5728010.0   5764980.0   5793636.0   5814422.0
70   46480882.0  46444832.0  46484062.0  46593236.0  46797754.0  47134837.0
71    1314545.0   1315407.0   1315790.0   1317384.0   1321977.0   1326898.0
75    5461512.0   5479531.0   5495303.0   5508214.0   5515525.0   5521606.0
77   66312067.0  66548272.0  66724104.0  66918020.0  67158348.0  67388001.0
81   64602298.0  65116219.0  65611593.0  66058859.0  66460344.0  66836327.0
89   10892413.0  10820883.0  10775971.0  10754679.0  10732882.0  10721582.0
99    4238389.0   4203604.0   4174349.0   4124531.0   4087843.0   4065253.0
101   9866468.0   9843028.0   9814023.0   9787966.0   9775564.0   9771141.0
111   4657740.0   4701957.0   4755335.0   4807388.0   4867316.0   4934340.0
116  60789140.0  60730582.0  60627498.0  60536709.0  60421760.0  59729081.0
143   2932367.0   2904910.0   2868231.0   2828403.0   2801543.0   2794137.0
144    556319.0    569604.0    582014.0    596336.0    607950.0    620001.0
145   1993782.0   1977527.0   1959537.0   1942248.0   1927174.0   1913822.0
157   2067471.0   2070226.0   2072490.0   2074502.0   2076217.0   2076694.0
177   5137232.0   5188607.0   5234519.0   5276968.0   5311916.0   5347896.0
190  38011735.0  37986412.0  37970087.0  37974826.0  37974750.0  37965475.0
194  10401062.0  10358076.0  10325452.0  10300300.0  10283822.0  10286263.0
201  19908979.0  19815616.0  19702267.0  19588715.0  19473970.0  19371648.0
221   5418649.0   5423801.0   5430798.0   5439232.0   5446771.0   5454147.0
222   2061980.0   2063531.0   2065042.0   2066388.0   2073894.0   2088385.0
223   9696110.0   9799186.0   9923085.0  10057698.0  10175214.0  10278887.0

           2020        2021        2022
14    8916864.0   8955797.0   9041851.0
17   11538604.0  11586195.0  11685814.0
21    6934015.0   6877743.0   6465097.0
37    8638167.0   8704546.0   8775760.0
54   10697858.0  10505772.0  10672118.0
55   83160871.0  83196078.0  83797985.0
58    5831404.0   5856733.0   5903037.0
70   47365655.0  47415794.0  47778340.0
71    1329522.0   1330932.0   1348840.0
75    5529543.0   5541017.0   5556106.0
77   67571107.0  67764304.0  67971311.0
81   67081234.0  67026292.0  66971395.0
89   10698599.0  10569207.0  10426919.0
99    4047680.0   3879000.0   3855600.0
101   9750149.0   9709891.0   9643048.0
111   4985382.0   5033164.0   5127170.0
116  59438851.0  59133173.0  58940425.0
143   2794885.0   2800839.0   2831639.0
144    630419.0    640064.0    653103.0
145   1900449.0   1884490.0   1879383.0
157   2072531.0   2065092.0   2057679.0
177   5379475.0   5408320.0   5457127.0
190  37899070.0  37747124.0  36821749.0
194  10297081.0  10361831.0  10409704.0
201  19265250.0  19122059.0  19047009.0
221   5458827.0   5447247.0   5431752.0
222   2102419.0   2108079.0   2111986.0
223  10353442.0  10415811.0  10486941.0   DataFrame with common Country Codes:
        Country Name Country Code        2011        2012        2013  \
14           Austria          AUT   8391643.0   8429991.0   8479823.0
17           Belgium          BEL  11038264.0  11106932.0  11159407.0
21          Bulgaria          BGR   7348328.0   7305888.0   7265115.0
37       Switzerland          CHE   7912398.0   7996861.0   8089346.0
54           Czechia          CZE  10496088.0  10510785.0  10514272.0
55           Germany          DEU  80274983.0  80425823.0  80645605.0
58           Denmark          DNK   5570572.0   5591572.0   5614932.0
70             Spain          ESP  46742697.0  46773055.0  46620045.0
71           Estonia          EST   1327439.0   1322696.0   1317997.0
75           Finland          FIN   5388272.0   5413971.0   5438972.0
77            France          FRA  65345233.0  65662240.0  66002289.0
81    United Kingdom          GBR  63258810.0  63700215.0  64128273.0
89            Greece          GRC  11104899.0  11045011.0  10965211.0
99           Croatia          HRV   4280622.0   4267558.0   4255689.0
101          Hungary          HUN   9971727.0   9920362.0   9893082.0
111          Ireland          IRL   4580084.0   4599533.0   4623816.0
116            Italy          ITA  59379449.0  59539717.0  60233948.0
143        Lithuania          LTU   3028115.0   2987773.0   2957689.0
144       Luxembourg          LUX    518347.0    530946.0    543360.0
145           Latvia          LVA   2059709.0   2034319.0   2012647.0
157  North Macedonia          MKD   2058539.0   2061044.0   2064032.0
177           Norway          NOR   4953088.0   5018573.0   5079623.0
190           Poland          POL  38063255.0  38063164.0  38040196.0
194         Portugal          PRT  10557560.0  10514844.0  10457295.0
201          Romania          ROU  20147528.0  20058035.0  19983693.0
221  Slovak Republic          SVK   5398384.0   5407579.0   5413393.0
222         Slovenia          SVN   2052843.0   2057159.0   2059953.0
223           Sweden          SWE   9449213.0   9519374.0   9600379.0

           2014        2015        2016        2017        2018        2019  \
14    8546356.0   8642699.0   8736668.0   8797566.0   8840521.0   8879920.0
17   11209057.0  11274196.0  11331422.0  11375158.0  11427054.0  11488980.0
21    7223938.0   7177991.0   7127822.0   7075947.0   7025037.0   6975761.0
37    8188649.0   8282396.0   8373338.0   8451840.0   8514329.0   8575280.0
54   10525347.0  10546059.0  10566332.0  10594438.0  10629928.0  10671870.0
55   80982500.0  81686611.0  82348669.0  82657002.0  82905782.0  83092962.0
58    5643475.0   5683483.0   5728010.0   5764980.0   5793636.0   5814422.0
70   46480882.0  46444832.0  46484062.0  46593236.0  46797754.0  47134837.0

In [24]:
def sort_by_country_code(df):
    return df.sort_values(by='Country Code')

# Apply the sorting function to each DataFrame
for i, df in enumerate(dataframes):
    dataframes[i] = sort_by_country_code(df)

# Display the sorted DataFrames
for i, df in enumerate(dataframes):
    print(f"{df} DataFrame sorted by Country Code:")
    print(df)
    print("\n" + "="*40 + "\n")  # Separating output for better readability

        Country Name Country Code          2011          2012          2013  \
14           Austria          AUT  42625.237350  39980.630840  41694.071410
17           Belgium          BEL  38266.983740  36945.841000  38766.038040
21          Bulgaria          BGR   6408.162620   6243.723979   6422.010445
37       Switzerland          CHE  70650.760300  68518.989360  69446.630990
54           Czechia          CZE  15447.399680  14334.344300  14511.859550
55           Germany          DEU  39563.817330  36959.968930  38946.313070
58           Denmark          DNK  51361.501820  48806.803020  51939.826360
70             Spain          ESP  26212.695890  23566.205090  24246.780770
71           Estonia          EST  13704.931510  13778.337230  15315.388440
75           Finland          FIN  41789.955880  38711.309790  40439.567250
77            France          FRA  37186.936050  34392.293850  35875.673830
81    United Kingdom          GBR  35752.958200  35519.330190  36085.945950
89            Greece          GRC  20268.839910  18108.189410  17844.248420
99           Croatia          HRV  11677.725470  10607.642930  11207.391370
101          Hungary          HUN  10941.720040  10013.359400  10828.651720
111          Ireland          IRL  35191.623130  32552.740140  35850.357050
116            Italy          ITA  31676.031770  28562.819180  28943.544610
143        Lithuania          LTU  12036.580420  12013.395370  13291.952250
144       Luxembourg          LUX  68844.401650  73525.228600  72403.408510
145           Latvia          LVA   9962.779893  10297.666030  11293.152100
157  North Macedonia          MKD   4003.648041   3678.204435   4130.954621
177           Norway          NOR  77792.246290  79207.141700  81275.574700
190           Poland          POL  11566.237160  11004.725190  11445.939400
194         Portugal          PRT  18736.508050  16374.401440  17588.490930
201          Romania          ROU   7534.116193   7016.996323   7498.974513
221  Slovak Republic          SVK  14577.732430  14119.209770  14882.058560
222         Slovenia          SVN  19709.885230  17479.583020  18184.308070
223           Sweden          SWE  51652.818110  49429.392370  52089.635280

             2014          2015          2016          2017          2018  \
14   42465.766610  35811.685780  37196.167750  38441.732720  41651.807390
17   39529.631060  33799.739830  34528.490590  36341.191070  39046.701410
21    6643.095885   5819.877624   6238.054937   6970.955514   7752.822898
37   68999.918110  66347.416160  63668.848940  63071.250220  63208.827090
54   14284.856690  12903.368090  13479.639180  15315.252110  17451.200670
55   40356.483120  34656.441910  35663.678890  37760.339680  40854.555970
58   53755.909090  45798.029800  46794.911370  49220.803910  52836.996120
70   24700.290100  21716.487970  22489.733440  23874.662000  25791.535570
71   16276.911330  14040.886020  14872.602420  16600.900750  18854.373310
75   41149.747880  35093.914640  35796.982580  37839.342440  40864.148370
77   36234.531200  30908.686330  31203.694850  32666.612560  34960.740760
81   39539.116500  37441.028420  34104.356810  34065.891030  36072.663210
89   17998.023520  15044.374440  14903.304930  15546.666000  16496.935840
99   11208.431820   9996.732777  10236.258320  11349.110950  12669.631860
101  11185.671090   9983.018368  10567.309640  11639.406170  13155.833800
111  38740.091700  34222.829920  35982.577770  38093.974820  41648.300450
116  29060.830990  24535.584580  25551.440400  26867.811920  28897.696280
143  14168.397870  11842.932740  12474.145430  14132.882990  16199.395140
144  75837.978480  55729.104160  58461.799890  66052.638050  69498.273760
145  11936.758860  10454.851660  11023.219060  12167.366130  13751.569190
157   4361.608148   3840.631976   4055.363776   4360.233546   4842.815446
177  78188.048940  61241.287330  58475.323880  61772.577710  66488.263380
190  11957.209040  10613.080620  10405.661260  11609.618130  13050.242230
194  17781.067520  15410.878010  16058.319570  17263.457030  18831.445310
201   8035.845581   7210.654432   7538.865946   8658.807084  10026.952130
221  15227.836610  13194.827100  13276.437400  14248.591610  15891.483960
222  18948.936690  15900.327560  16741.112050  18495.236350  20777.206770
223  51104.430770  43373.545430  43610.186700  45639.940560  46269.208670

             2019          2020          2021  2022
14   40712.575340  39515.557410  43281.733480   NaN
17   38340.122000  36801.281740  41743.014280   NaN
21    8165.632881   8311.253957  10114.523520   NaN
37   62588.336180  62971.416170  69631.658240   NaN
54   17471.655290  16844.235110  19843.782910   NaN
55   39718.002330  39043.097150  42982.481890   NaN
58   50967.611500  52242.031370  58796.359930   NaN
70   25125.871720  22321.683940  25118.453140   NaN
71   19062.769490  19133.100650  22462.364750   NaN
75   39659.405240  40405.343870  44416.200200   NaN
77   33895.528770  31922.266090  36489.804090   NaN
81            NaN           NaN           NaN   NaN
89   16155.113670  14754.743490  17262.586540   NaN
99   12740.008500  11828.053960  14553.412930   NaN
101  13651.960480  12911.789030  14799.383800   NaN
111  42297.147920  39973.740210  49607.175420   NaN
116  28011.165480  26185.782590  29681.557130   NaN
143  16457.095730  17108.310660  19957.147930   NaN
144  62146.077050  66535.389550  77781.175700   NaN
145  13837.831740  14147.461270  16238.889760   NaN
157   4780.283819   4769.857803   5334.163986   NaN
177  60649.023130  53949.802500  69953.019230   NaN
190  13241.256600  13333.543280  15098.239660   NaN
194  18587.777080  17471.065560  19318.467560   NaN
201  10527.767510  10801.983540  12194.363630   NaN
221  15653.308220  15875.115630  17386.339380   NaN
222  20799.559780  20345.776110  23493.474900   NaN
223  44558.122930  45322.007070  51830.626610   NaN   DataFrame sorted by Country Code:
        Country Name Country Code          2011          2012          2013  \
14           Austria          AUT  42625.237350  39980.630840  41694.071410
17           Belgium          BEL  38266.983740  36945.841000  38766.038040
21          Bulgaria          BGR   6408.162620   6243.723979   6422.010445
37       Switzerland          CHE  70650.760300  68518.989360  69446.630990
54           Czechia          CZE  15447.399680  14334.344300  14511.859550
55           Germany          DEU  39563.817330  36959.968930  38946.313070
58           Denmark          DNK  51361.501820  48806.803020  51939.826360
70             Spain          ESP  26212.695890  23566.205090  24246.780770
71           Estonia          EST  13704.931510  13778.337230  15315.388440
75           Finland          FIN  41789.955880  38711.309790  40439.567250
77            France          FRA  37186.936050  34392.293850  35875.673830
81    United Kingdom          GBR  35752.958200  35519.330190  36085.945950
89            Greece          GRC  20268.839910  18108.189410  17844.248420
99           Croatia          HRV  11677.725470  10607.642930  11207.391370
101          Hungary          HUN  10941.720040  10013.359400  10828.651720
111          Ireland          IRL  35191.623130  32552.740140  35850.357050
116            Italy          ITA  31676.031770  28562.819180  28943.544610
143        Lithuania          LTU  12036.580420  12013.395370  13291.952250
144       Luxembourg          LUX  68844.401650  73525.228600  72403.408510
145           Latvia          LVA   9962.779893  10297.666030  11293.152100
157  North Macedonia          MKD   4003.648041   3678.204435   4130.954621
177           Norway          NOR  77792.246290  79207.141700  81275.574700
190           Poland          POL  11566.237160  11004.725190  11445.939400
194         Portugal          PRT  18736.508050  16374.401440  17588.490930
201          Romania          ROU   7534.116193   7016.996323   7498.974513
221  Slovak Republic          SVK  14577.732430  14119.209770  14882.058560
222         Slovenia          SVN  19709.885230  17479.583020  18184.308070
223           Sweden          SWE  51652.818110  49429.392370  52089.635280

             2014          2015          2016          2017          2018  \
14   42465.766610  35811.685780  37196.167750  38441.732720  41651.807390
17   39529.631060  33799.739830  34528.490590  36341.191070  39046.701410
21    6643.095885   5819.877624   6238.054937   6970.955514   7752.822898
37   68999.918110  66347.416160  63668.848940  63071.250220  63208.827090
54   14284.856690  12903.368090  13479.639180  15315.252110  17451.200670
55   40356.483120  34656.441910  35663.678890  37760.339680  40854.555970
58   53755.909090  45798.029800  46794.911370  49220.803910  52836.996120
70   24700.290100  21716.487970  22489.733440  23874.662000  25791.535570
71   16276.911330  14040.886020  14872.602420  16600.900750  18854.373310
75   41149.747880  35093.914640  35796.982580  37839.342440  40864.148370
77   36234.531200  30908.686330  31203.694850  32666.612560  34960.740760
81   39539.116500  37441.028420  34104.356810  34065.891030  36072.663210
89   17998.023520  15044.374440  14903.304930  15546.666000  16496.935840
99   11208.431820   9996.732777  10236.258320  11349.110950  12669.631860
101  11185.671090   9983.018368  10567.309640  11639.406170  13155.833800
111  38740.091700  34222.829920  35982.577770  38093.974820  41648.300450
116  29060.830990  24535.584580  25551.440400  26867.811920  28897.696280
143  14168.397870  11842.932740  12474.145430  14132.882990  16199.395140
144  75837.978480  55729.104160  58461.799890  66052.638050  69498.273760
145  11936.758860  10454.851660  11023.219060  12167.366130  13751.569190
157   4361.608148   3840.631976   4055.363776   4360.233546   4842.815446
177  78188.048940  61241.287330  58475.323880  61772.577710  66488.263380
190  11957.209040  10613.080620  10405.661260  11609.618130  13050.242230
194  17781.067520  15410.878010  16058.319570  17263.457030  18831.445310
201   8035.845581   7210.654432   7538.865946   8658.807084  10026.952130
221  15227.836610  13194.827100  13276.437400  14248.591610  15891.483960
222  18948.936690  15900.327560  16741.112050  18495.236350  20777.206770
223  51104.430770  43373.545430  43610.186700  45639.940560  46269.208670

             2019          2020          2021  2022
14   40712.575340  39515.557410  43281.733480   NaN
17   38340.122000  36801.281740  41743.014280   NaN
21    8165.632881   8311.253957  10114.523520   NaN
37   62588.336180  62971.416170  69631.658240   NaN
54   17471.655290  16844.235110  19843.782910   NaN
55   39718.002330  39043.097150  42982.481890   NaN
58   50967.611500  52242.031370  58796.359930   NaN
70   25125.871720  22321.683940  25118.453140   NaN
71   19062.769490  19133.100650  22462.364750   NaN
75   39659.405240  40405.343870  44416.200200   NaN
77   33895.528770  31922.266090  36489.804090   NaN
81            NaN           NaN           NaN   NaN
89   16155.113670  14754.743490  17262.586540   NaN
99   12740.008500  11828.053960  14553.412930   NaN
101  13651.960480  12911.789030  14799.383800   NaN
111  42297.147920  39973.740210  49607.175420   NaN
116  28011.165480  26185.782590  29681.557130   NaN
143  16457.095730  17108.310660  19957.147930   NaN
144  62146.077050  66535.389550  77781.175700   NaN
145  13837.831740  14147.461270  16238.889760   NaN
157   4780.283819   4769.857803   5334.163986   NaN
177  60649.023130  53949.802500  69953.019230   NaN
190  13241.256600  13333.543280  15098.239660   NaN
194  18587.777080  17471.065560  19318.467560   NaN
201  10527.767510  10801.983540  12194.363630   NaN
221  15653.308220  15875.115630  17386.339380   NaN
222  20799.559780  20345.776110  23493.474900   NaN
223  44558.122930  45322.007070  51830.626610   NaN

========================================

        Country Name Country Code        2011        2012        2013  \
14           Austria          AUT   8391643.0   8429991.0   8479823.0
17           Belgium          BEL  11038264.0  11106932.0  11159407.0
21          Bulgaria          BGR   7348328.0   7305888.0   7265115.0
37       Switzerland          CHE   7912398.0   7996861.0   8089346.0
54           Czechia          CZE  10496088.0  10510785.0  10514272.0
55           Germany          DEU  80274983.0  80425823.0  80645605.0
58           Denmark          DNK   5570572.0   5591572.0   5614932.0
70             Spain          ESP  46742697.0  46773055.0  46620045.0
71           Estonia          EST   1327439.0   1322696.0   1317997.0
75           Finland          FIN   5388272.0   5413971.0   5438972.0
77            France          FRA  65345233.0  65662240.0  66002289.0
81    United Kingdom          GBR  63258810.0  63700215.0  64128273.0
89            Greece          GRC  11104899.0  11045011.0  10965211.0
99           Croatia          HRV   4280622.0   4267558.0   4255689.0
101          Hungary          HUN   9971727.0   9920362.0   9893082.0
111          Ireland          IRL   4580084.0   4599533.0   4623816.0
116            Italy          ITA  59379449.0  59539717.0  60233948.0
143        Lithuania          LTU   3028115.0   2987773.0   2957689.0
144       Luxembourg          LUX    518347.0    530946.0    543360.0
145           Latvia          LVA   2059709.0   2034319.0   2012647.0
157  North Macedonia          MKD   2058539.0   2061044.0   2064032.0
177           Norway          NOR   4953088.0   5018573.0   5079623.0
190           Poland          POL  38063255.0  38063164.0  38040196.0
194         Portugal          PRT  10557560.0  10514844.0  10457295.0
201          Romania          ROU  20147528.0  20058035.0  19983693.0
221  Slovak Republic          SVK   5398384.0   5407579.0   5413393.0
222         Slovenia          SVN   2052843.0   2057159.0   2059953.0
223           Sweden          SWE   9449213.0   9519374.0   9600379.0

           2014        2015        2016        2017        2018        2019  \
14    8546356.0   8642699.0   8736668.0   8797566.0   8840521.0   8879920.0
17   11209057.0  11274196.0  11331422.0  11375158.0  11427054.0  11488980.0
21    7223938.0   7177991.0   7127822.0   7075947.0   7025037.0   6975761.0
37    8188649.0   8282396.0   8373338.0   8451840.0   8514329.0   8575280.0
54   10525347.0  10546059.0  10566332.0  10594438.0  10629928.0  10671870.0
55   80982500.0  81686611.0  82348669.0  82657002.0  82905782.0  83092962.0
58    5643475.0   5683483.0   5728010.0   5764980.0   5793636.0   5814422.0
70   46480882.0  46444832.0  46484062.0  46593236.0  46797754.0  47134837.0
71    1314545.0   1315407.0   1315790.0   1317384.0   1321977.0   1326898.0
75    5461512.0   5479531.0   5495303.0   5508214.0   5515525.0   5521606.0
77   66312067.0  66548272.0  66724104.0  66918020.0  67158348.0  67388001.0
81   64602298.0  65116219.0  65611593.0  66058859.0  66460344.0  66836327.0
89   10892413.0  10820883.0  10775971.0  10754679.0  10732882.0  10721582.0
99    4238389.0   4203604.0   4174349.0   4124531.0   4087843.0   4065253.0
101   9866468.0   9843028.0   9814023.0   9787966.0   9775564.0   9771141.0
111   4657740.0   4701957.0   4755335.0   4807388.0   4867316.0   4934340.0
116  60789140.0  60730582.0  60627498.0  60536709.0  60421760.0  59729081.0
143   2932367.0   2904910.0   2868231.0   2828403.0   2801543.0   2794137.0
144    556319.0    569604.0    582014.0    596336.0    607950.0    620001.0
145   1993782.0   1977527.0   1959537.0   1942248.0   1927174.0   1913822.0
157   2067471.0   2070226.0   2072490.0   2074502.0   2076217.0   2076694.0
177   5137232.0   5188607.0   5234519.0   5276968.0   5311916.0   5347896.0
190  38011735.0  37986412.0  37970087.0  37974826.0  37974750.0  37965475.0
194  10401062.0  10358076.0  10325452.0  10300300.0  10283822.0  10286263.0
201  19908979.0  19815616.0  19702267.0  19588715.0  19473970.0  19371648.0
221   5418649.0   5423801.0   5430798.0   5439232.0   5446771.0   5454147.0
222   2061980.0   2063531.0   2065042.0   2066388.0   2073894.0   2088385.0
223   9696110.0   9799186.0   9923085.0  10057698.0  10175214.0  10278887.0

           2020        2021        2022
14    8916864.0   8955797.0   9041851.0
17   11538604.0  11586195.0  11685814.0
21    6934015.0   6877743.0   6465097.0
37    8638167.0   8704546.0   8775760.0
54   10697858.0  10505772.0  10672118.0
55   83160871.0  83196078.0  83797985.0
58    5831404.0   5856733.0   5903037.0
70   47365655.0  47415794.0  47778340.0
71    1329522.0   1330932.0   1348840.0
75    5529543.0   5541017.0   5556106.0
77   67571107.0  67764304.0  67971311.0
81   67081234.0  67026292.0  66971395.0
89   10698599.0  10569207.0  10426919.0
99    4047680.0   3879000.0   3855600.0
101   9750149.0   9709891.0   9643048.0
111   4985382.0   5033164.0   5127170.0
116  59438851.0  59133173.0  58940425.0
143   2794885.0   2800839.0   2831639.0
144    630419.0    640064.0    653103.0
145   1900449.0   1884490.0   1879383.0
157   2072531.0   2065092.0   2057679.0
177   5379475.0   5408320.0   5457127.0
190  37899070.0  37747124.0  36821749.0
194  10297081.0  10361831.0  10409704.0
201  19265250.0  19122059.0  19047009.0
221   5458827.0   5447247.0   5431752.0
222   2102419.0   2108079.0   2111986.0
223  10353442.0  10415811.0  10486941.0   DataFrame sorted by Country Code:
        Country Name Country Code        2011        2012        2013  \
14           Austria          AUT   8391643.0   8429991.0   8479823.0
17           Belgium          BEL  11038264.0  11106932.0  11159407.0
21          Bulgaria          BGR   7348328.0   7305888.0   7265115.0
37       Switzerland          CHE   7912398.0   7996861.0   8089346.0
54           Czechia          CZE  10496088.0  10510785.0  10514272.0
55           Germany          DEU  80274983.0  80425823.0  80645605.0
58           Denmark          DNK   5570572.0   5591572.0   5614932.0
70             Spain          ESP  46742697.0  46773055.0  46620045.0
71           Estonia          EST   1327439.0   1322696.0   1317997.0
75           Finland          FIN   5388272.0   5413971.0   5438972.0
77            France          FRA  65345233.0  65662240.0  66002289.0
81    United Kingdom          GBR  63258810.0  63700215.0  64128273.0
89            Greece          GRC  11104899.0  11045011.0  10965211.0
99           Croatia          HRV   4280622.0   4267558.0   4255689.0
101          Hungary          HUN   9971727.0   9920362.0   9893082.0
111          Ireland          IRL   4580084.0   4599533.0   4623816.0
116            Italy          ITA  59379449.0  59539717.0  60233948.0
143        Lithuania          LTU   3028115.0   2987773.0   2957689.0
144       Luxembourg          LUX    518347.0    530946.0    543360.0
145           Latvia          LVA   2059709.0   2034319.0   2012647.0
157  North Macedonia          MKD   2058539.0   2061044.0   2064032.0
177           Norway          NOR   4953088.0   5018573.0   5079623.0
190           Poland          POL  38063255.0  38063164.0  38040196.0
194         Portugal          PRT  10557560.0  10514844.0  10457295.0
201          Romania          ROU  20147528.0  20058035.0  19983693.0
221  Slovak Republic          SVK   5398384.0   5407579.0   5413393.0
222         Slovenia          SVN   2052843.0   2057159.0   2059953.0
223           Sweden          SWE   9449213.0   9519374.0   9600379.0

           2014        2015        2016        2017        2018        2019  \
14    8546356.0   8642699.0   8736668.0   8797566.0   8840521.0   8879920.0
17   11209057.0  11274196.0  11331422.0  11375158.0  11427054.0  11488980.0
21    7223938.0   7177991.0   7127822.0   7075947.0   7025037.0   6975761.0
37    8188649.0   8282396.0   8373338.0   8451840.0   8514329.0   8575280.0
54   10525347.0  10546059.0  10566332.0  10594438.0  10629928.0  10671870.0
55   80982500.0  81686611.0  82348669.0  82657002.0  82905782.0  83092962.0
58    5643475.0   5683483.0   5728010.0   5764980.0   5793636.0   5814422.0
70   46480882.0  46444832.0  46484062.0  46593236.0  46797754.0  47134837.0

In [31]:

# List of DataFrames
dataframes = [income_df, population_df, rail_df, air_df]

def reindex_rows(df):
    df.reset_index(drop=True, inplace=True)
    return df

# Apply the reindexing function to each DataFrame
for i, df in enumerate(dataframes):
    dataframes[i] = reindex_rows(df)

# Display the modified original DataFrames with reindexed rows
for i, df in enumerate(dataframes):
    print(f"{df} DataFrame with reindexed rows:")
    print(df)
    print("\n" + "="*40 + "\n")  # Separating output for better readability

       Country Name Country Code          2011          2012          2013  \
0           Albania          ALB   3753.965485   3522.372857   3757.696946
1           Austria          AUT  42625.237350  39980.630840  41694.071410
2           Belgium          BEL  38266.983740  36945.841000  38766.038040
3          Bulgaria          BGR   6408.162620   6243.723979   6422.010445
4       Switzerland          CHE  70650.760300  68518.989360  69446.630990
5            Cyprus          CYP  29378.478520  25145.888670  23695.255860
6           Czechia          CZE  15447.399680  14334.344300  14511.859550
7           Germany          DEU  39563.817330  36959.968930  38946.313070
8           Denmark          DNK  51361.501820  48806.803020  51939.826360
9             Spain          ESP  26212.695890  23566.205090  24246.780770
10          Estonia          EST  13704.931510  13778.337230  15315.388440
11          Finland          FIN  41789.955880  38711.309790  40439.567250
12           France          FRA  37186.936050  34392.293850  35875.673830
13   United Kingdom          GBR  35752.958200  35519.330190  36085.945950
14           Greece          GRC  20268.839910  18108.189410  17844.248420
15          Croatia          HRV  11677.725470  10607.642930  11207.391370
16          Hungary          HUN  10941.720040  10013.359400  10828.651720
17          Ireland          IRL  35191.623130  32552.740140  35850.357050
18          Iceland          ISL  32094.720220  32294.153180  39104.098090
19            Italy          ITA  31676.031770  28562.819180  28943.544610
20        Lithuania          LTU  12036.580420  12013.395370  13291.952250
21       Luxembourg          LUX  68844.401650  73525.228600  72403.408510
22           Latvia          LVA   9962.779893  10297.666030  11293.152100
23  North Macedonia          MKD   4003.648041   3678.204435   4130.954621
24       Montenegro          MNE   6553.322168   5887.144304   6424.363178
25      Netherlands          NLD  44453.574190  40527.215080  42399.313950
26           Norway          NOR  77792.246290  79207.141700  81275.574700
27           Poland          POL  11566.237160  11004.725190  11445.939400
28         Portugal          PRT  18736.508050  16374.401440  17588.490930
29          Romania          ROU   7534.116193   7016.996323   7498.974513
30           Serbia          SRB   5472.781189   4879.443718   5535.674049
31  Slovak Republic          SVK  14577.732430  14119.209770  14882.058560
32         Slovenia          SVN  19709.885230  17479.583020  18184.308070
33           Sweden          SWE  51652.818110  49429.392370  52089.635280
34          Turkiye          TUR   9534.737344   9895.728768  10665.187200

            2014          2015          2016          2017          2018  \
0    3844.277141   3277.788243   3467.347570   3729.968219   4340.919854
1   42465.766610  35811.685780  37196.167750  38441.732720  41651.807390
2   39529.631060  33799.739830  34528.490590  36341.191070  39046.701410
3    6643.095885   5819.877624   6238.054937   6970.955514   7752.822898
4   68999.918110  66347.416160  63668.848940  63071.250220  63208.827090
5   22731.183590  20165.851560  20629.857420  22676.039060  24887.570310
6   14284.856690  12903.368090  13479.639180  15315.252110  17451.200670
7   40356.483120  34656.441910  35663.678890  37760.339680  40854.555970
8   53755.909090  45798.029800  46794.911370  49220.803910  52836.996120
9   24700.290100  21716.487970  22489.733440  23874.662000  25791.535570
10  16276.911330  14040.886020  14872.602420  16600.900750  18854.373310
11  41149.747880  35093.914640  35796.982580  37839.342440  40864.148370
12  36234.531200  30908.686330  31203.694850  32666.612560  34960.740760
13  39539.116500  37441.028420  34104.356810  34065.891030  36072.663210
14  17998.023520  15044.374440  14903.304930  15546.666000  16496.935840
15  11208.431820   9996.732777  10236.258320  11349.110950  12669.631860
16  11185.671090   9983.018368  10567.309640  11639.406170  13155.833800
17  38740.091700  34222.829920  35982.577770  38093.974820  41648.300450
18  43168.214110  42267.312470  49914.179370  58236.912050  58426.799150
19  29060.830990  24535.584580  25551.440400  26867.811920  28897.696280
20  14168.397870  11842.932740  12474.145430  14132.882990  16199.395140
21  75837.978480  55729.104160  58461.799890  66052.638050  69498.273760
22  11936.758860  10454.851660  11023.219060  12167.366130  13751.569190
23   4361.608148   3840.631976   4055.363776   4360.233546   4842.815446
24   6523.412900   5880.513496   6166.840414   7028.304223   7834.487269
25  43058.080460  36999.532440  37170.143760  40003.301820  43940.042400
26  78188.048940  61241.287330  58475.323880  61772.577710  66488.263380
27  11957.209040  10613.080620  10405.661260  11609.618130  13050.242230
28  17781.067520  15410.878010  16058.319570  17263.457030  18831.445310
29   8035.845581   7210.654432   7538.865946   8658.807084  10026.952130
30   5426.731356   4584.557262   4679.413515   5026.221826   5868.807072
31  15227.836610  13194.827100  13276.437400  14248.591610  15891.483960
32  18948.936690  15900.327560  16741.112050  18495.236350  20777.206770
33  51104.430770  43373.545430  43610.186700  45639.940560  46269.208670
34  10269.293410   9294.272812   9193.574206   8921.211220   8063.601198

            2019          2020          2021  2022
0    4361.999293   4322.549675   5262.913596   NaN
1   40712.575340  39515.557410  43281.733480   NaN
2   38340.122000  36801.281740  41743.014280   NaN
3    8165.632881   8311.253957  10114.523520   NaN
4   62588.336180  62971.416170  69631.658240   NaN
5   24414.591800  22488.416020  24687.482420   NaN
6   17471.655290  16844.235110  19843.782910   NaN
7   39718.002330  39043.097150  42982.481890   NaN
8   50967.611500  52242.031370  58796.359930   NaN
9   25125.871720  22321.683940  25118.453140   NaN
10  19062.769490  19133.100650  22462.364750   NaN
11  39659.405240  40405.343870  44416.200200   NaN
12  33895.528770  31922.266090  36489.804090   NaN
13           NaN           NaN           NaN   NaN
14  16155.113670  14754.743490  17262.586540   NaN
15  12740.008500  11828.053960  14553.412930   NaN
16  13651.960480  12911.789030  14799.383800   NaN
17  42297.147920  39973.740210  49607.175420   NaN
18  57484.496090  48009.386200  54204.424350   NaN
19  28011.165480  26185.782590  29681.557130   NaN
20  16457.095730  17108.310660  19957.147930   NaN
21  62146.077050  66535.389550  77781.175700   NaN
22  13837.831740  14147.461270  16238.889760   NaN
23   4780.283819   4769.857803   5334.163986   NaN
24   7878.679567   6828.855865   8483.015981   NaN
25  42706.659130  41293.757370  46419.707120   NaN
26  60649.023130  53949.802500  69953.019230   NaN
27  13241.256600  13333.543280  15098.239660   NaN
28  18587.777080  17471.065560  19318.467560   NaN
29  10527.767510  10801.983540  12194.363630   NaN
30   5940.804379   6351.269736   7431.640563   NaN
31  15653.308220  15875.115630  17386.339380   NaN
32  20799.559780  20345.776110  23493.474900   NaN
33  44558.122930  45322.007070  51830.626610   NaN
34   7621.523127   7197.801955           NaN   NaN   DataFrame with reindexed rows:
       Country Name Country Code          2011          2012          2013  \
0           Albania          ALB   3753.965485   3522.372857   3757.696946
1           Austria          AUT  42625.237350  39980.630840  41694.071410
2           Belgium          BEL  38266.983740  36945.841000  38766.038040
3          Bulgaria          BGR   6408.162620   6243.723979   6422.010445
4       Switzerland          CHE  70650.760300  68518.989360  69446.630990
5            Cyprus          CYP  29378.478520  25145.888670  23695.255860
6           Czechia          CZE  15447.399680  14334.344300  14511.859550
7           Germany          DEU  39563.817330  36959.968930  38946.313070
8           Denmark          DNK  51361.501820  48806.803020  51939.826360
9             Spain          ESP  26212.695890  23566.205090  24246.780770
10          Estonia          EST  13704.931510  13778.337230  15315.388440
11          Finland          FIN  41789.955880  38711.309790  40439.567250
12           France          FRA  37186.936050  34392.293850  35875.673830
13   United Kingdom          GBR  35752.958200  35519.330190  36085.945950
14           Greece          GRC  20268.839910  18108.189410  17844.248420
15          Croatia          HRV  11677.725470  10607.642930  11207.391370
16          Hungary          HUN  10941.720040  10013.359400  10828.651720
17          Ireland          IRL  35191.623130  32552.740140  35850.357050
18          Iceland          ISL  32094.720220  32294.153180  39104.098090
19            Italy          ITA  31676.031770  28562.819180  28943.544610
20        Lithuania          LTU  12036.580420  12013.395370  13291.952250
21       Luxembourg          LUX  68844.401650  73525.228600  72403.408510
22           Latvia          LVA   9962.779893  10297.666030  11293.152100
23  North Macedonia          MKD   4003.648041   3678.204435   4130.954621
24       Montenegro          MNE   6553.322168   5887.144304   6424.363178
25      Netherlands          NLD  44453.574190  40527.215080  42399.313950
26           Norway          NOR  77792.246290  79207.141700  81275.574700
27           Poland          POL  11566.237160  11004.725190  11445.939400
28         Portugal          PRT  18736.508050  16374.401440  17588.490930
29          Romania          ROU   7534.116193   7016.996323   7498.974513
30           Serbia          SRB   5472.781189   4879.443718   5535.674049
31  Slovak Republic          SVK  14577.732430  14119.209770  14882.058560
32         Slovenia          SVN  19709.885230  17479.583020  18184.308070
33           Sweden          SWE  51652.818110  49429.392370  52089.635280
34          Turkiye          TUR   9534.737344   9895.728768  10665.187200

            2014          2015          2016          2017          2018  \
0    3844.277141   3277.788243   3467.347570   3729.968219   4340.919854
1   42465.766610  35811.685780  37196.167750  38441.732720  41651.807390
2   39529.631060  33799.739830  34528.490590  36341.191070  39046.701410
3    6643.095885   5819.877624   6238.054937   6970.955514   7752.822898
4   68999.918110  66347.416160  63668.848940  63071.250220  63208.827090
5   22731.183590  20165.851560  20629.857420  22676.039060  24887.570310
6   14284.856690  12903.368090  13479.639180  15315.252110  17451.200670
7   40356.483120  34656.441910  35663.678890  37760.339680  40854.555970
8   53755.909090  45798.029800  46794.911370  49220.803910  52836.996120
9   24700.290100  21716.487970  22489.733440  23874.662000  25791.535570
10  16276.911330  14040.886020  14872.602420  16600.900750  18854.373310
11  41149.747880  35093.914640  35796.982580  37839.342440  40864.148370
12  36234.531200  30908.686330  31203.694850  32666.612560  34960.740760
13  39539.116500  37441.028420  34104.356810  34065.891030  36072.663210
14  17998.023520  15044.374440  14903.304930  15546.666000  16496.935840
15  11208.431820   9996.732777  10236.258320  11349.110950  12669.631860
16  11185.671090   9983.018368  10567.309640  11639.406170  13155.833800
17  38740.091700  34222.829920  35982.577770  38093.974820  41648.300450
18  43168.214110  42267.312470  49914.179370  58236.912050  58426.799150
19  29060.830990  24535.584580  25551.440400  26867.811920  28897.696280
20  14168.397870  11842.932740  12474.145430  14132.882990  16199.395140
21  75837.978480  55729.104160  58461.799890  66052.638050  69498.273760
22  11936.758860  10454.851660  11023.219060  12167.366130  13751.569190
23   4361.608148   3840.631976   4055.363776   4360.233546   4842.815446
24   6523.412900   5880.513496   6166.840414   7028.304223   7834.487269
25  43058.080460  36999.532440  37170.143760  40003.301820  43940.042400
26  78188.048940  61241.287330  58475.323880  61772.577710  66488.263380
27  11957.209040  10613.080620  10405.661260  11609.618130  13050.242230
28  17781.067520  15410.878010  16058.319570  17263.457030  18831.445310
29   8035.845581   7210.654432   7538.865946   8658.807084  10026.952130
30   5426.731356   4584.557262   4679.413515   5026.221826   5868.807072
31  15227.836610  13194.827100  13276.437400  14248.591610  15891.483960
32  18948.936690  15900.327560  16741.112050  18495.236350  20777.206770
33  51104.430770  43373.545430  43610.186700  45639.940560  46269.208670
34  10269.293410   9294.272812   9193.574206   8921.211220   8063.601198

            2019          2020          2021  2022
0    4361.999293   4322.549675   5262.913596   NaN
1   40712.575340  39515.557410  43281.733480   NaN
2   38340.122000  36801.281740  41743.014280   NaN
3    8165.632881   8311.253957  10114.523520   NaN
4   62588.336180  62971.416170  69631.658240   NaN
5   24414.591800  22488.416020  24687.482420   NaN
6   17471.655290  16844.235110  19843.782910   NaN
7   39718.002330  39043.097150  42982.481890   NaN
8   50967.611500  52242.031370  58796.359930   NaN
9   25125.871720  22321.683940  25118.453140   NaN
10  19062.769490  19133.100650  22462.364750   NaN
11  39659.405240  40405.343870  44416.200200   NaN
12  33895.528770  31922.266090  36489.804090   NaN
13           NaN           NaN           NaN   NaN
14  16155.113670  14754.743490  17262.586540   NaN
15  12740.008500  11828.053960  14553.412930   NaN
16  13651.960480  12911.789030  14799.383800   NaN
17  42297.147920  39973.740210  49607.175420   NaN
18  57484.496090  48009.386200  54204.424350   NaN
19  28011.165480  26185.782590  29681.557130   NaN
20  16457.095730  17108.310660  19957.147930   NaN
21  62146.077050  66535.389550  77781.175700   NaN
22  13837.831740  14147.461270  16238.889760   NaN
23   4780.283819   4769.857803   5334.163986   NaN
24   7878.679567   6828.855865   8483.015981   NaN
25  42706.659130  41293.757370  46419.707120   NaN
26  60649.023130  53949.802500  69953.019230   NaN
27  13241.256600  13333.543280  15098.239660   NaN
28  18587.777080  17471.065560  19318.467560   NaN
29  10527.767510  10801.983540  12194.363630   NaN
30   5940.804379   6351.269736   7431.640563   NaN
31  15653.308220  15875.115630  17386.339380   NaN
32  20799.559780  20345.776110  23493.474900   NaN
33  44558.122930  45322.007070  51830.626610   NaN
34   7621.523127   7197.801955           NaN   NaN

========================================

       Country Name Country Code        2011        2012        2013  \
0           Albania          ALB   2905195.0   2900401.0   2895092.0
1           Austria          AUT   8391643.0   8429991.0   8479823.0
2           Belgium          BEL  11038264.0  11106932.0  11159407.0
3          Bulgaria          BGR   7348328.0   7305888.0   7265115.0
4       Switzerland          CHE   7912398.0   7996861.0   8089346.0
5            Cyprus          CYP   1145086.0   1156556.0   1166968.0
6           Czechia          CZE  10496088.0  10510785.0  10514272.0
7           Germany          DEU  80274983.0  80425823.0  80645605.0
8           Denmark          DNK   5570572.0   5591572.0   5614932.0
9             Spain          ESP  46742697.0  46773055.0  46620045.0
10          Estonia          EST   1327439.0   1322696.0   1317997.0
11          Finland          FIN   5388272.0   5413971.0   5438972.0
12           France          FRA  65345233.0  65662240.0  66002289.0
13   United Kingdom          GBR  63258810.0  63700215.0  64128273.0
14           Greece          GRC  11104899.0  11045011.0  10965211.0
15          Croatia          HRV   4280622.0   4267558.0   4255689.0
16          Hungary          HUN   9971727.0   9920362.0   9893082.0
17          Ireland          IRL   4580084.0   4599533.0   4623816.0
18          Iceland          ISL    319014.0    320716.0    323764.0
19            Italy          ITA  59379449.0  59539717.0  60233948.0
20    Liechtenstein          LIE     36189.0     36505.0     36806.0
21        Lithuania          LTU   3028115.0   2987773.0   2957689.0
22       Luxembourg          LUX    518347.0    530946.0    543360.0
23           Latvia          LVA   2059709.0   2034319.0   2012647.0
24  North Macedonia          MKD   2058539.0   2061044.0   2064032.0
25            Malta          MLT    416268.0    420028.0    425967.0
26       Montenegro          MNE    620079.0    620601.0    621207.0
27      Netherlands          NLD  16693074.0  16754962.0  16804432.0
28           Norway          NOR   4953088.0   5018573.0   5079623.0
29           Poland          POL  38063255.0  38063164.0  38040196.0
30         Portugal          PRT  10557560.0  10514844.0  10457295.0
31          Romania          ROU  20147528.0  20058035.0  19983693.0
32           Serbia          SRB   7234099.0   7199077.0   7164132.0
33  Slovak Republic          SVK   5398384.0   5407579.0   5413393.0
34         Slovenia          SVN   2052843.0   2057159.0   2059953.0
35           Sweden          SWE   9449213.0   9519374.0   9600379.0
36          Turkiye          TUR  74223629.0  75175827.0  76147624.0

          2014        2015        2016        2017        2018        2019  \
0    2889104.0   2880703.0   2876101.0   2873457.0   2866376.0   2854191.0
1    8546356.0   8642699.0   8736668.0   8797566.0   8840521.0   8879920.0
2   11209057.0  11274196.0  11331422.0  11375158.0  11427054.0  11488980.0
3    7223938.0   7177991.0   7127822.0   7075947.0   7025037.0   6975761.0
4    8188649.0   8282396.0   8373338.0   8451840.0   8514329.0   8575280.0
5    1176995.0   1187280.0   1197881.0   1208523.0   1218831.0   1228836.0
6   10525347.0  10546059.0  10566332.0  10594438.0  10629928.0  10671870.0
7   80982500.0  81686611.0  82348669.0  82657002.0  82905782.0  83092962.0
8    5643475.0   5683483.0   5728010.0   5764980.0   5793636.0   5814422.0
9   46480882.0  46444832.0  46484062.0  46593236.0  46797754.0  47134837.0
10   1314545.0   1315407.0   1315790.0   1317384.0   1321977.0   1326898.0
11   5461512.0   5479531.0   5495303.0   5508214.0   5515525.0   5521606.0
12  66312067.0  66548272.0  66724104.0  66918020.0  67158348.0  67388001.0
13  64602298.0  65116219.0  65611593.0  66058859.0  66460344.0  66836327.0
14  10892413.0  10820883.0  10775971.0  10754679.0  10732882.0  10721582.0
15   4238389.0   4203604.0   4174349.0   4124531.0   4087843.0   4065253.0
16   9866468.0   9843028.0   9814023.0   9787966.0   9775564.0   9771141.0
17   4657740.0   4701957.0   4755335.0   4807388.0   4867316.0   4934340.0
18    327386.0    330815.0    335439.0    343400.0    352721.0    360563.0
19  60789140.0  60730582.0  60627498.0  60536709.0  60421760.0  59729081.0
20     37096.0     37355.0     37609.0     37889.0     38181.0     38482.0
21   2932367.0   2904910.0   2868231.0   2828403.0   2801543.0   2794137.0
22    556319.0    569604.0    582014.0    596336.0    607950.0    620001.0
23   1993782.0   1977527.0   1959537.0   1942248.0   1927174.0   1913822.0
24   2067471.0   2070226.0   2072490.0   2074502.0   2076217.0   2076694.0
25    434558.0    445053.0    455356.0    467999.0    484630.0    504062.0
26    621810.0    622159.0    622303.0    622373.0    622227.0    622028.0
27  16865008.0  16939923.0  17030314.0  17131296.0  17231624.0  17344874.0
28   5137232.0   5188607.0   5234519.0   5276968.0   5311916.0   5347896.0
29  38011735.0  37986412.0  37970087.0  37974826.0  37974750.0  37965475.0
30  10401062.0  10358076.0  10325452.0  10300300.0  10283822.0  10286263.0
31  19908979.0  19815616.0  19702267.0  19588715.0  19473970.0  19371648.0
32   7130576.0   7095383.0   7058322.0   7020858.0   6982604.0   6945235.0
33   5418649.0   5423801.0   5430798.0   5439232.0   5446771.0   5454147.0
34   2061980.0   2063531.0   2065042.0   2066388.0   2073894.0   2088385.0
35   9696110.0   9799186.0   9923085.0  10057698.0  10175214.0  10278887.0
36  77181884.0  78218479.0  79277962.0  80312698.0  81407204.0  82579440.0

          2020        2021        2022
0    2837849.0   2811666.0   2777689.0

In [32]:
def check_same_country_codes(dataframes):
    # Extract unique "Country Code" values from the first DataFrame
    reference_codes = set(dataframes[0]['Country Code'].unique())

    # Check if all other DataFrames have the same "Country Code" values
    for df in dataframes[1:]:
        if set(df['Country Code'].unique()) != reference_codes:
            return False

    return True

# Check if all DataFrames have the same "Country Code" values
result = check_same_country_codes(dataframes)

# Display the result
if result:
    print("All DataFrames have the same set of Country Codes.")
else:
    print("Not all DataFrames have the same set of Country Codes.")

Not all DataFrames have the same set of Country Codes.

In [33]:
income_df

,Country Name,Country Code,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Albania,ALB,3753.965485,3522.372857,3757.696946,3844.277141,3277.788243,3467.347570,3729.968219,4340.919854,4361.999293,4322.549675,5262.913596,NaN
1,Austria,AUT,42625.237350,39980.630840,41694.071410,42465.766610,35811.685780,37196.167750,38441.732720,41651.807390,40712.575340,39515.557410,43281.733480,NaN
2,Belgium,BEL,38266.983740,36945.841000,38766.038040,39529.631060,33799.739830,34528.490590,36341.191070,39046.701410,38340.122000,36801.281740,41743.014280,NaN
3,Bulgaria,BGR,6408.162620,6243.723979,6422.010445,6643.095885,5819.877624,6238.054937,6970.955514,7752.822898,8165.632881,8311.253957,10114.523520,NaN
4,Switzerland,CHE,70650.760300,68518.989360,69446.630990,68999.918110,66347.416160,63668.848940,63071.250220,63208.827090,62588.336180,62971.416170,69631.658240,NaN
5,Cyprus,CYP,29378.478520,25145.888670,23695.255860,22731.183590,20165.851560,20629.857420,22676.039060,24887.570310,24414.591800,22488.416020,24687.482420,NaN
6,Czechia,CZE,15447.399680,14334.344300,14511.859550,14284.856690,12903.368090,13479.639180,15315.252110,17451.200670,17471.655290,16844.235110,19843.782910,NaN
7,Germany,DEU,39563.817330,36959.968930,38946.313070,40356.483120,34656.441910,35663.678890,37760.339680,40854.555970,39718.002330,39043.097150,42982.481890,NaN
8,Denmark,DNK,51361.501820,48806.803020,51939.826360,53755.909090,45798.029800,46794.911370,49220.803910,52836.996120,50967.611500,52242.031370,58796.359930,NaN
9,Spain,ESP,26212.695890,23566.205090,24246.780770,24700.290100,21716.487970,22489.733440,23874.662000,25791.535570,25125.871720,22321.683940,25118.453140,NaN
10,Estonia,EST,13704.931510,13778.337230,15315.388440,16276.911330,14040.886020,14872.602420,16600.900750,18854.373310,19062.769490,19133.100650,22462.364750,NaN
11,Finland,FIN,41789.955880,38711.309790,40439.567250,41149.747880,35093.914640,35796.982580,37839.342440,40864.148370,39659.405240,40405.343870,44416.200200,NaN
12,France,FRA,37186.936050,34392.293850,35875.673830,36234.531200,30908.686330,31203.694850,32666.612560,34960.740760,33895.528770,31922.266090,36489.804090,NaN
13,United Kingdom,GBR,35752.958200,35519.330190,36085.945950,39539.116500,37441.028420,34104.356810,34065.891030,36072.663210,NaN,NaN,NaN,NaN
14,Greece,GRC,20268.839910,18108.189410,17844.248420,17998.023520,15044.374440,14903.304930,15546.666000,16496.935840,16155.113670,14754.743490,17262.586540,NaN
15,Croatia,HRV,11677.725470,10607.642930,11207.391370,11208.431820,9996.732777,10236.258320,11349.110950,12669.631860,12740.008500,11828.053960,14553.412930,NaN
16,Hungary,HUN,10941.720040,10013.359400,10828.651720,11185.671090,9983.018368,10567.309640,11639.406170,13155.833800,13651.960480,12911.789030,14799.383800,NaN
17,Ireland,IRL,35191.623130,32552.740140,35850.357050,38740.091700,34222.829920,35982.577770,38093.974820,41648.300450,42297.147920,39973.740210,49607.175420,NaN
18,Iceland,ISL,32094.720220,32294.153180,39104.098090,43168.214110,42267.312470,49914.179370,58236.912050,58426.799150,57484.496090,48009.386200,54204.424350,NaN
19,Italy,ITA,31676.031770,28562.819180,28943.544610,29060.830990,24535.584580,25551.440400,26867.811920,28897.696280,28011.165480,26185.782590,29681.557130,NaN
20,Lithuania,LTU,12036.580420,12013.395370,13291.952250,14168.397870,11842.932740,12474.145430,14132.882990,16199.395140,16457.095730,17108.310660,19957.147930,NaN
21,Luxembourg,LUX,68844.401650,73525.228600,72403.408510,75837.978480,55729.104160,58461.799890,66052.638050,69498.273760,62146.077050,66535.389550,77781.175700,NaN
22,Latvia,LVA,9962.779893,10297.666030,11293.152100,11936.758860,10454.851660,11023.219060,12167.366130,13751.569190,13837.831740,14147.461270,16238.889760,NaN
23,North Macedonia,MKD,4003.648041,3678.204435,4130.954621,4361.608148,3840.631976,4055.363776,4360.233546,4842.815446,4780.283819,4769.857803,5334.163986,NaN
24,Montenegro,MNE,6553.322168,5887.144304,6424.363178,6523.412900,5880.513496,6166.840414,7028.304223,7834.487269,7878.679567,6828.855865,8483.015981,NaN
25,Netherlands,NLD,44453.574190,40527.215080,42399.313950,43058.080460,36999.532440,37170.143760,40003.301820,43940.042400,42706.659130,41293.757370,46419.707120,NaN
26,Norway,NOR,77792.246290,79207.141700,81275.574700,78188.048940,61241.287330,58475.323880,61772.577710,66488.263380,60649.023130,53949.802500,69953.019230,NaN
27,Poland,POL,11566.237160,11004.725190,11445.939400,11957.209040,10613.080620,10405.661260,11609.618130,13050.242230,13241.256600,13333.543280,15098.239660,NaN
28,Portugal,PRT,18736.508050,16374.401440,17588.490930,17781.067520,15410.878010,16058.319570,17263.457030,18831.445310,18587.777080,17471.065560,19318.467560,NaN
29,Romania,ROU,7534.116193,7016.996323,7498.974513,8035.845581,7210.654432,7538.865946,8658.807084,10026.952130,10527.767510,10801.983540,12194.363630,NaN
30,Serbia,SRB,5472.781189,4879.443718,5535.674049,5426.731356,4584.557262,4679.413515,5026.221826,5868.807072,5940.804379,6351.269736,7431.640563,NaN
31,Slovak Republic,SVK,14577.732430,14119.209770,14882.058560,15227.836610,13194.827100,13276.437400,14248.591610,15891.483960,15653.308220,15875.115630,17386.339380,NaN
32,Slovenia,SVN,19709.885230,17479.583020,18184.308070,18948.936690,15900.327560,16741.112050,18495.236350,20777.206770,20799.559780,20345.776110,23493.474900,NaN
33,Sweden,SWE,51652.818110,49429.392370,52089.635280,51104.430770,43373.545430,43610.186700,45639.940560,46269.208670,44558.122930,45322.007070,51830.626610,NaN
34,Turkiye,TUR,9534.737344,9895.728768,10665.187200,10269.293410,9294.272812,9193.574206,8921.211220,8063.601198,7621.523127,7197.801955,NaN,NaN